### ISSUE TITLE
Piwigo on iOS does NOT strip GPS location data on upload

### ISSUE THREAD

**Issue by mmajchr** [Piwigo/Piwigo-Mobile#108]
This is violation of users privacy. Even if in some(?) cases it might be "useful". The general approach (or at least an option in settings) should be to strip gps location data.

**Comment by EddyLB** [comment]
That is now implemented and to be released in a future release once other things are completed. Would you be interested in testing a beta version through TestFlight until then ?

**Comment by mmajchr** [comment]
Of course I would love to testflight it :D

**Comment by EddyLB** [comment]
Send me your [email](piwigo@lelievre-berna.net) address so that I can add you to the [TestFlight](https://itunes.apple.com/us/app/testflight/id899247664?mt=8) list of testers.

**Comment by mmajchr** [comment]
Easier said than done ;) I have Google'd some email that looks to be yours and send message don't know if that was what you meant ;)

**Comment by EddyLB** [comment]
Click on "[email](piwigo@lelievre-berna.net)" in my previous post or use the email of my GitHub account (public).

**Comment by mmajchr** [comment]
I think done, check mail :)

**Comment by EddyLB** [comment]
Yes, thanks.

**Comment by mmajchr** [comment]
I have installed version from testflight but looks it doesn't have it yet (2.0.2) :) Just reporting ;)

**Comment by EddyLB** [comment]
Yes, the Strip GPS Metadata option will appear in 2.0.3. I cannot submit 2.0.3 with TestFlight until the 2.0.2 is available on the AppStore (waiting for Apple...).

**Comment by mmajchr** [comment]
Works AWESOME !!! :)

**Comment by EddyLB** [comment]
Thank you 👍
