### ISSUE TITLE
Incompatibility with Piwigo plugin Community

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#117]
When the plugin [Community](http://piwigo.org/ext/extension_view.php?eid=303) is installed and activated, the albums and photos are not presented as expected.

To be solved with Pierrick…

**Comment by plegall** [comment]
Hi @EddyLB 

The "problem" is that Piwigo Mobile for iOS does both feature : browsing and upload. Not many remote applications do that. Plugin Community assumes that you do "upload", not "browse" this is why https://github.com/plegall/Piwigo-community/blob/master/main.inc.php#L281 :

```
// the plugin Community is activated, the user has upload permissions, we
// use a specific function to list available categories, assuming the user
// wants to list categories where upload is possible for him
```

To make things simpler, it means that if you're not an admin and only a user with Community upload permissions, method pwg.categories.getList will only return the list of albums where you have upload permission.

I also mention that method pwg.categories.getAdminList gives the full list of all albums, without taking permissions into account. Of course, this method only works for administrators (or webmasters).

To improve things, we would need to have a specific method : community.categories.getList. And the ability to tell Community not to "fake" the result of pwg.categories.getList. This can be done! The most important is to avoid breaking all other remote applications relying on the current way Community works.

**Comment by plegall** [comment]
Give a look at https://github.com/plegall/Piwigo-community/commit/bb9f033a96f72d8cae86b8784910b664025aa613

Do you need an environment to test it?

**Comment by mmajchr** [comment]
I can confirm Community extension is enabled our server 😄

**Comment by EddyLB** [comment]
Thank you @mmajchr

**Comment by EddyLB** [comment]
Yes @plegall, an environment for testing it would be really useful.
Do I understand correctly that the iOS app should first determine if the Community extension is installed and active with `piwigo.pluginsGetList` and then use `piwigo.categories.getList` or `community.categories.getList` ?

**Comment by plegall** [comment]
@EddyLB you should have received an email with the URL to your testing environment, with plugin Community including latest commits.

So here is the procedure:
```
if (method "community.session.getStatus" exists)
{
  // plugin Community is installed, in version 2.9.a or newer
  $result = callMethod("community.session.getStatus");

  // either pwg.categories.getAdminList or community.categories.getList
  $methodToCall = $result["upload_categories_getList_method"];
}
else
{
  // either plugin Community is not installed or in an old version
  $result = callMethod("pwg.session.getStatus");

  if ($result['status'] == 'webmaster' or $result['status'] == 'admin')
  {
    $methodToCall = "pwg.categories.getAdminList";
  }
  else
  {
    $methodToCall = "pwg.categories.getList";
  }
}
```

**Comment by mmajchr** [comment]
Do I understand correctly that after those fixes Piwigo for iOS will still NOT work with "old" Community plugin ?
Maybe it would be much easier and MORE compatible with all versions to do browsing requests ONLY as NOT logged user ?

**Comment by plegall** [comment]
If @EddyLB implements the algorithm the way I recommend earlier, the iOS will work the same way as currently with old versions of Community plugin. By the way, I don't see why you wouldn't update Community. It's so easy!

**Comment by mmajchr** [comment]
Well the point is to work better and not "the same way".  Also it doesn't matter if update is "easy" or not. I just think that forcing it is a bad practice. He can implement it "the way you recommend" but I would change last else to instead of using old/broken code list albums as not logged user. Really sending requests as unauthorized user isn't much of an issue and introduced FULL compatybility. Besides AFAIK he ONLY needs album ID for upload so no need to be logged for that 😄

**Comment by plegall** [comment]
@mmajchr making some requests as "not logged in user" makes no sense to me because it doesn't solve the problem at all :-/ Community plugin can give upload permissions for not logged in users. And more importantly, user "john" may not see the same albums as "guest" (ie not logged in user), so I don't think it's a good idea at all to change this behavior.

Updating Community is not a problem. It's a 1 click operation.

**Comment by mmajchr** [comment]
Can update be done NOW ? 😄 In other words does current version of Community plugin have all these new APIs ? 😄

**Comment by plegall** [comment]
@mmajchr The current of Community (ie 2.8.a) does not have the new API methods. I can release a new version when @EddyLB tells me he's fine with my changes. I have other big changes in preparation for Community, but I can release a version 2.9.a with just the API improvements.

**Comment by EddyLB** [comment]
@plegall, the infos provided on the [Piwigo web API explorer](http://piwigo.org/demo/tools/ws.htm#top) are quite succinct.

What is difference between `pwg.categories.getAdminList` and `pwg.categories.getList` when logged as Admin/Webmaster ? What is the benefit of using `pwg.categories.getAdminList` ?

**Comment by plegall** [comment]
@EddyLB `getAdminList` will return the whole list, without taking the permissions into account (just like the list in the web administration of Piwigo). `pwg.categories.getList` takes the permissions into account. Yes, permissions apply to administrators.

One small note: for a normal user, `pwg.categories.getList` does not return empty albums, while administrators get the empty albums (I'm 92% sure).

**Comment by EddyLB** [comment]
@plegall, the 2.1 alpha version is in progress and albums show up as expected.
Would now be great to solve https://github.com/plegall/Piwigo-community/issues/24 and https://github.com/plegall/Piwigo-community/issues/25.

**Comment by mmajchr** [comment]
I can tell that now albums are displayed correctly for me. However app starts in root of all albums so I have to ALWAYS open my own albums. In case our server it looks like this. After logging app displays only one album "Users" in root, which is correct for displaying but still I cannot upload anything in there. When I open "Users" I get dozens of albums of different users which is correct but I still cannot upload anything, I have to scroll trough all of that find my user name and open MY "root album" and then I am "at home" :) Can't app detect what is users "root album" and start there? And if not maybe it could be added as an option?

**Comment by EddyLB** [comment]
Thank you @mmajchr for your feedback.

- The album tree you get is the one adopted by your Piwigo webmaster. It might be useful to ask him/her why the Piwigo server content is organised this way. As of today, there is no easy way to detect the root user album but we may consider adding a settings option for Community users.
- You are certainly annoyed by the fact that the app returns automatically to the root album each time you leave and return to it (e.g. using multitasking). This is a known issue #165 which will be fixed in the next build.

**Comment by mmajchr** [comment]
I like how albums are organised on server. I am just informing that previous versions of your app returned ONLY folders that I could upload to, this one reports ALL 😄 If this is expected behavior then definitely we need an option for "start album" 😃

**Comment by EddyLB** [comment]
Ok, I've opened the issue #167.
