### ISSUE TITLE
ipad, edit photo button does nothing

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#126]
When you're on a single photo, if you open the top-right menu (which should have a more appropriate icon in my opinion), the "edit" action button has no effect. The edit page does not open at all. It works fine on my iphone 6s.

![piwigo-ios-ipad-bug-edit](https://cloud.githubusercontent.com/assets/9326959/26349088/1037b49a-3faf-11e7-8944-d91409210b66.jpg)

Device : ipad 4, Piwigo Mobile 2.0.3 (20), iOS 10.3.1

**Comment by EddyLB** [comment]
Thanks. I can reproduce the issue with the simulator and a warning appears in the console.
I shall try to fix that in 2.0.4.

**Comment by plegall** [comment]
I don't see the commit which fixes this bug :-/ Or maybe it was fixed with another commit and now the bug can't be reproduced?

**Comment by EddyLB** [comment]
Sorry… now done.
