### ISSUE TITLE
Menu overlap

### ISSUE THREAD

**Issue by yarez0** [Piwigo/Piwigo-Mobile#161]
Hi, 

I notice a menu overlap, when playing video (video js plugin) in portrait mode, when I want to play in full screen it doesn't work, but when I push the subtitle button the app is playing in full screen mode, then there is an overlap when quitting the full screen mode

photo 1 : no full screen
http://imageshack.com/a/img924/3977/G2xZXt.png

photo 2 : full screen when touching the subtitle button
http://imageshack.com/a/img924/817/Xo84kF.png

photo 3 : overlap menu 
http://imageshack.com/a/img923/6198/HVJJO6.png

**Comment by EddyLB** [comment]
Can be fixed by replacing the deprecated code mentioned in #166.

**Comment by EddyLB** [comment]
Fixed with #166
