### ISSUE TITLE
Auto-connection cannot be changed before timeout

### ISSUE THREAD

**Issue by yarez0** [Piwigo/Piwigo-Mobile#164]
Hi, 

I noticed that when an URL is configured in the app, when the app is lunch again (days or month after), the app keep the configuration. then when I lunch it again, the app try to connect to the URL, so if I want to change it, I have to wait the timeout before reconfiguring the new URL

(when I do tests with local / internet URL)

**Comment by EddyLB** [comment]
Exact. That should be fixed in the next release [v2.1.3](https://github.com/Piwigo/Piwigo-Mobile/milestone/8).
