### ISSUE TITLE
Replace the root album with a Default Album

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#167]
Sometimes, the user root album is not located in the main root album of the Piwigo server.
Should we add a settings option for Community users to allow them to always get their own root album after logging in (instead of the Piwigo root album) ?

**Comment by mmajchr** [comment]
I vote for 👍 😄

**Comment by EddyLB** [comment]
May be even better would be to define a Favorite album, i.e. the ’working album’ into which we use to add or comment photos. It might also be used to upload in the background photos taken with Camera.

Ideas ? Comments ?

**Comment by mmajchr** [comment]
If app would start from some album name IMHO doesn't matter 😄 Important is to NOT always scroll trough hundreds of albums to get yours 😸

**Comment by sectroyer** [comment]
Any progress with that?

**Comment by EddyLB** [comment]
Yes, I have tested some ideas and I envisage to add a swipe-right command allowing to set an album "being edited" (like the swipe-left command for deleting, renaming or moving an album). In the future, this album will be used to automatically upload photos/videos recorded with Photos in the background.

**Comment by sectroyer** [comment]
Great, scrolling trough dozens of other user albums it's really annoying 👍 Waiting for your "fix" 😄

**Comment by EddyLB** [comment]
Finally, after having tested different ideas, the next release will introduce an improved Upload view allowing to Set a Default Album and to Create Sub-Albums.

**Comment by sectroyer** [comment]
Can't wait 👍

**Comment by plegall** [comment]
I am testing 2.2 (113) and I don't understand how the "default album" is supposed to work :-/

Once I set an album as "default album", I go back to the thumbnails and I have a "home" icon next to the "upload" icône (bottom right)

**Comment by EddyLB** [comment]
The idea consists in "replacing temporarily" the root album with a Default Album. This way you can limit the navigation inside a specific album. This can be useful for working on a project. At login, the app always opens this album instead of the root album. To return to the root album, you simply tap the home icon (same icon as on the Piwigo web interface). An alternative could be to code the app so that it always comes back to the last opened album after logout/login but that would not be the same functionality.

I am going to ask beta testers about their feeling. I would like to determine whether there is a consensus on the way to set it: in the Preferences section or in the Upload section.

**Comment by EddyLB** [comment]
Introduced in version 2.2
