### ISSUE TITLE
Community plugin — Create album

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#170]
As of version 2.1, it is not possible to create an album in an album for which the user has upload rights. This is clearly a missing action but the app needs to know whether the user is authorised. To be investigated…

**Comment by EddyLB** [comment]
Method [requested](https://github.com/plegall/Piwigo-community/issues/35) to add this functionality.

**Comment by thymon13** [comment]
Hi! 

Some news ? :-)

**Comment by EddyLB** [comment]
Was recently discussed with Pierrick. Please be patient.

**Comment by hencisk** [comment]
Hello! Any news for this? Would be really needed to handle all upload process via mobile app.

**Comment by hencisk** [comment]
Sorry, for being so active into reported issues here, but know, I really love this IOS app, it's super user friendly and intuitive!!!
But as there is such a silence in Community plugin development, could be an option here to allow "Create Sub-Album" always, but display an error, if rights are missing after or album creation method fails? 
Seems similarly it's realized in Android "Piwigo Client" app, where Community plugin users can create an sub-folder, where currently it's totally impossible in IOS and only option is to create it first via Web and then use app instead.
Of course it will a bit mislead users not having album creation rights, but probably this could be improved setting this behavior only, if Community plugin is present on the server.

**Comment by EddyLB** [comment]
Hi @hencisk , will make some tests and see what we can do the next release.

**Comment by EddyLB** [comment]
Hi @hencisk ,
A beta of the next version 2.4.5 now allows Community users to create albums. It should return an error if the Community users does not have the appropriate rights. Would you like to test it with TestFlight?

**Comment by hencisk** [comment]
Hi!
Absolutelly. Please send an invite.

HK
________________________________

**Comment by hencisk** [comment]
It works perfectly!!! 👍👍👍
Thank you very match!
________________________________

**Comment by EddyLB** [comment]
Thank you.
