### ISSUE TITLE
Version 2.1.1 + Community 2.8 = app blocked on login

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#174]
In an issue related to Community, @EddyLB wrote:

... to be complete, the app does the following right after login:
1. `pwg.session.getStatus`, check if Piwigo version >= 2.7, get available sizes
2. `reflection.getMethodList`, check if `community.session.getStatus` is available
3. if Community is available `community.session.getStatus` and get real user status
4. if user has admin rights execute `pwg.plugins.getList` to determine if VideoJS is installed.

... and here is my answer :

There is a problem in this sequence. On an old (or actually, any current) version of Community, pwg.session.getStatus will reply "status=admin" and you will execute step 4 with pwg.plugins.getList :-/ Unfortunately, this API method is not in the list of methods authorized for non-admin users. So it fails :

> connection error - request failed: unauthorised (401)

and it does that right on the login screen, impossible to go further in the app.

A user reported me that issue on Piwigo.com, so I could implement a quick fix (I authorized pwg.plugins.getList for users with Community permissions), but that will be a big issue outside Piwigo.com.

**Comment by EddyLB** [comment]
Sorry for that. Looks like all beta testers use Community 2.9a…

The app first performs `reflection.getMethodList` to determine if a recent version of Community is installed and then perform `pwg.session.login`, `community.session.getStatus`, `pwg.session.getStatus` and finally `pwg.plugins.getList`. The user status is not updated when calling pwg.session.getStatus if Community >2.9a is installed.

In the case where an 'old' version of Community is used, the app behaves as if Community is not installed and that indeed leads to this issue. Indeed, the app should only call`pwg.plugins.getList` if the user is a true admin, which can only be known when Community >2.9a is installed.

**Comment by plegall** [comment]
Using `pwg.plugins.getList` to know if VideoJS is activated and thus if the user can upload videos is not the right way to go, in my opinion.

In the information returned by `pwg.session.getStatus` you have `upload_file_types`. If Community is active and VideoJS (or maybe other plugins in the future), you have:

> "upload_file_types":"jpg,jpeg,png,gif,mp4,tif,tiff,ogg,ogv,m4v,webm,webmv"

And that should be enough to know if the iOS app can upload videos.

For now, if you have Community + VideoJS + `$conf['upload_form_all_types'] = true;` then a Community user will be able to upload videos BUT I may certainly add a configuration setting in Community saying "this permission allows video upload, or not". You should better rely on `upload_file_types` returned by `pwg.session.getStatus` :-)

**Comment by EddyLB** [comment]
Many thanks @plegall . I'm going to investigate this option.
I've started to work on this project a very few months ago and obviously need some time and help to understand the philosophy and capabilities of the Web API.

**Comment by EddyLB** [comment]
@plegall , could you please check that the version 2.1.2 now available through TestFlight fixes this issue ?

**Comment by EddyLB** [comment]
Approved by TestFlight users.
