### ISSUE TITLE
PNG screenshot compressed to JPEG

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#195]
Hi @EddyLB 

I often use the iOS app to upload screenshots from my iphone to a Piwigo. Unfortunately, and I think it's a recent change, even if in my preferences I have ""Resize Before Upload" disabled, the screenshot uploaded keeps the "*.PNG" extension but it has become a compressed JPEG file.

Would it be possible to keep the original file without any compression?

**Comment by EddyLB** [comment]
Hi @plegall 

I've checked the code and the app is coded from the early days so that images are converted to JPEG and slightly compressed (95%) unless the user wishes to resize/compress it differently. 

I agree that it should keep the original file and I'm going to correct that.

**Comment by EddyLB** [comment]
Fixed while replacing ALAssetLibrary (#115)
