### ISSUE TITLE
Option to delete after upload

### ISSUE THREAD

**Issue by TallGuysFreeADMIN** [Piwigo/Piwigo-Mobile#202]
iOS 11 allows apps to delete photos (well, call a prompt asking the user). It would be amazing if Piwigo could add this basic function as a **setting** (not mandatory) ("Delete from device after upload"). 

Photos that are deleted go into the built in iOS "Recently Deleted" album.

**Comment by EddyLB** [comment]
Being working on #115 (on some evenings and week-ends), I shall try to implement that option in the next release.
