### ISSUE TITLE
http basic authentication

### ISSUE THREAD

**Issue by jessie-github** [Piwigo/Piwigo-Mobile#203]
To secure my Piwigo server installation (piwigo.example.com), I am using nginx with http basic authentication (or basic access authentication).
Normally it's possible to use the credentials directly in the URL, like https://username:password@piwigo.example.com

I used this URL (with embedded credentials) as server URL in Piwigo Mobile and it seems to work. Except that the pictures don't appear (I only got the folder and pictures names).

It seems that it isn't missing much to make Piwigo Mobile compatible with http basic authentication.
Can I then propose a feature request/enhancement to make Piwigo Mobile compatible with http basic authentication ?

Thanks

**Comment by EddyLB** [comment]
The actual version of Piwigo Mobile is compatible with basic http authentication.
Have you tried to enter the credentials in the login/pwd fields ?

**Comment by jessie-github** [comment]
@EddyLB I don't have username/password field for http basic authentication (i.e. basic access authentication), I only have the fields for Piwigo username/password.

**Comment by jessie-github** [comment]
@EddyLB What ? It seems that if I enter the http basic authentication credentials in the Piwigo username/password fields, I manage to access the server !
Is this some kind of mixed username/password fields ?
How can I enter the Piwigo username/password then ?

**Comment by EddyLB** [comment]
Exact. For the moment, the idea is that you can either use the standard Piwigo credentials OR the HTTP(S) credentials. So if you access your site using https://username:password@piwigo.example.com, select HTTPS, enter the address "piwigo.example.com" as URL, username in Login and password in the password field.

**Comment by EddyLB** [comment]
Two-factor authentication is not implemented. Is this what you look for?

**Comment by jessie-github** [comment]
@EddyLB But what happens if I want to use both (Piwigo credentials and HTTP credentials)
The username/password for HTTP credentials can be embedded in the URL but the Piwigo credentials can not. So perhaps it would be best to retrieve the HTTP credentials from the URL instead of using this mixed fields ?

And no I am not looking at 2-factor authentication, I am using Piwigo behind HTTP basic authentication.

**Comment by EddyLB** [comment]
The username/password for HTTP credentials are also used for Piwigo logging in.

**Comment by jessie-github** [comment]
Yes I understand that.
Let me reformulate.
I have the following single HTTP credentials dummy_user/dummy_password and I have a lot of Piwigo users (with access to different albums). For instance the user jessie has the following Piwigo credentials jessie/mysecretpassword.

So I have to enter somewhere dummy_user/dummy_password AND jessie/mysecretpassword.
I don't understand how I can do that.

**Comment by EddyLB** [comment]
Ok, so you need a sort of two-factor authentication: credentials for HTTPS authentication and credentials for Piwigo authentication. I'm sorry to have to tell that it is not possible today. The only solution for the moment is to use the same credentials for both, which means to append a list of credentials in your Apache settings.

I may consider adding an option for entering HTTP credentials in Settings in a future release.

**Comment by jessie-github** [comment]
Oh I thought you were talking about 2FA OTP (token based).

An option to enter HTTP credentials would be nice indeed.
However it is almost working as it is. If I enter the HTTP credentials in the URL and the Piwigo credentials in the fields, I have access to the server (so the HTTP credentials are correctly transferred) and the Piwigo user albums (so the Piwigo credentials are correctly transferred) !
It's just that the pictures don't appear, so there is something different between the pictures management and the path management.

**Comment by EddyLB** [comment]
Yes, this is normal because the app then uses the Piwigo credentials as HTTP credentials. Having the HTTP credentials visible on the interface is also not acceptable.
I must introduce a way to enter HTTP credentials in Settings or elsewhere. I will have a thought about that considering the evolution of the app I am preparing.
Bye for now.

**Comment by EddyLB** [comment]
The next version will prompt an alert asking HTTP credentials when the server is set to request basic access authentication. It will then store them in the keychain. Would you accept to test the next release 2.1.6 ?

**Comment by jessie-github** [comment]
> Would you accept to test the next release 2.1.6 ?

Of course, I will test the next release and report the result here.
Thanks

**Comment by EddyLB** [comment]
Great. Are you already registered for testing the app with [TestFlight](https://itunes.apple.com/us/app/testflight/id899247664?mt=8) ? If not, can you please send your email address to [me](mailto:piwigo@lelievre-berna.net) so that I can add you to the list of beta testers?

**Comment by jessie-github** [comment]
It works perfectly on 2.1.6, you can close the issue I think. Except if you want me to test some other edge case ?

**Comment by EddyLB** [comment]
Great. Thank you very much for testing and for your feedback. I therefore close this issue but please do not hesitate to open new ones on any subject you might wish.
