### ISSUE TITLE
iPad: Login Screen

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#21]
Make the login screen different in landscape, with the logo on the one side and the fields on the other.

**Comment by kcergfalo** [comment]
Hi Spencer,
please have a look at the pull request. It should address the rotating of the iPad for the login screen

- Olaf

**Comment by SpencerBaker** [comment]
Done. 72da252a5befc7ef47529f97ef0431ca99663828
