### ISSUE TITLE
Uploading Video on Piwigo

### ISSUE THREAD

**Issue by msandtheman** [Piwigo/Piwigo-Mobile#215]
I am trying to find a simple way to upload a simple plugin that will allow me to upload videos on my Piwigo site. Everything on the web assumes the user is a computer programmer. I have limited computer skills and need something very simple. Is this possible for a Piwigo user? or do I have to go to college and become a computer expert. I am sorry for the sarcasm, but I have spent hours trying to figure this out with no success. I really like the Piwigo software and appreciate all the work you folks have put into it.

**Comment by EddyLB** [comment]
Hi msandtheman,
To be able to upload videos to your Piwigo server, you have to install the extension [VideoJS](http://piwigo.org/ext/extension_view.php?eid=610) on your Piwigo server and edit the Piwigo configuration. So the first question is: Do you have admin access to your Piwigo server?

PS: This page is dedicated to the iOS app and what you look for is some help for changing the settings of your server. The [Piwigo forum](http://piwigo.org/forum/) would be a more appropriate place for posting your request.

**Comment by msandtheman** [comment]
Thank you very much. Your response was fast. I will try the other site.

**Comment by EddyLB** [comment]
If you have admin access to your Piwigo, try to follow the instructions provided [here](https://github.com/xbgmsharp/piwigo-videojs/wiki).

**Comment by msandtheman** [comment]
Eddy,
    Thank you very much for your help.
    The instructions you are giving me are a little above my abilities.
Luckily I have a friend that can help. I will see if he and I can do this
together.


Best Regards,
Michael Sandholzer
