### ISSUE TITLE
force HTTPS for *.piwigo.com

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#219]
If the url is *.piwigo.com, the mobile app can (and should) force to HTTPS.

On Piwigo.com, we're going to force redirection, but not on POST request and on ws.php, to avoid issues with remote applications like ios app. If the ios app could smartly switch to HTTPS, it would be more secure for user data :-)

**Comment by EddyLB** [comment]
Thanks for the suggestion. I'm going to change the app so that HTTPS becomes the default protocol. The app will propose to switch to HTTP in case of error.

**Comment by EddyLB** [comment]
Done
