### ISSUE TITLE
incorrect orientation

### ISSUE THREAD

**Issue by mbruno222** [Piwigo/Piwigo-Mobile#222]
In the latest app store version 2.1.8 all vertical images now have the incorrect rotation on the website. It seems that the original image is rotated prior to being uploaded, but that the orientation metadata tag in the image still says that it is rotated 90 degrees, and hence the website is applying a second rotation.
Previously all vertical images uploaded from the iPhone app did not have a rotation applied to the actual image and the website was applying it based on the orientation metadata tag.

**Comment by EddyLB** [comment]
I do not encounter this issue. Can you please tell me what type of iPhone and iOS do you use?

**Comment by mbruno222** [comment]
It's an iPhone 5c with iOS 10.3.3

**Comment by mbruno222** [comment]
Commit 458659b looks like it should be removing the orientation information, but vertical images uploaded with the latest version still have an orientation of 90 degrees in the metadata.

**Comment by EddyLB** [comment]
To my knowledge, Piwigo uses the EXIF width/height metadata to determine the orientation of an image. Can you please check the metadata of the uploaded images ? Don't you get width < height  for portraits ?

**Comment by EddyLB** [comment]
I now realise that the result depends on the format selected in the Settings of the iOS device. A portrait is well displayed by the Piwigo server if it was stored in the iOS device in HEIC format, but not in JPEG! So I'm going to investigate…

**Comment by thymon13** [comment]
Thanks !! I’ve the same issue
