### ISSUE TITLE
version 2.1.8 no longer smartly compatible with Community

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#223]
Version 2.1 had introduced smart detection of Community plugin installed on Piwigo and requested the right API methods. The idea was to avoid listing only the upload albums on the "Albums" tab of the app, see #117 

Version 2.1.8 seems to go back to the old behavior, we only see the upload albums. Here is a log of ws.php.

1. First with Community 2.8.a

```
[2018-05-10 12:40:43]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.logout',
)
[2018-05-10 12:40:46]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.login',
  'password' => 'verysecret',
  'username' => 'plg2',
)
[2018-05-10 12:40:46]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.getStatus',
)
[2018-05-10 12:40:47]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.categories.getList',
  'cat_id' => '0',
  'faked_by_community' => 'true',
  'recursive' => 'false',
)
```

2. Then with Community 2.9.a-beta

```
[2018-05-10 12:38:49]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.logout',
)
[2018-05-10 12:38:57]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.login',
  'password' => 'verysecret',
  'username' => 'plg2',
)
[2018-05-10 12:38:58]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.session.getStatus',
)
[2018-05-10 12:38:58]   [INFO]  ws.php, REQUEST = array (
  'format' => 'json',
  'method' => 'pwg.categories.getList',
  'cat_id' => '0',
  'faked_by_community' => 'true',
  'recursive' => 'false',
)
```

As we can see, the iOS app does not try to know if community is installed (no call to `reflection.getMethodList` to know if `community.categories.getList` is available) and directly ask `pwg.categories.getList` faked by Community

**Comment by plegall** [comment]
More tests have shown that this problem was specific to HTTP as opposed to HTTPS (on HTTPS we have another problem).

**Comment by EddyLB** [comment]
Indeed, when the server is not accessible in HTTPS mode, the version 2.1.8:

1. calls `reflection.getMethodList` and fails (should be visible in `error.logs`),
2. suggests the HTTP mode to the user,
3. does not call again `reflection.getMethodList` as it should before doing further.

Will be fixed very soon.
