### ISSUE TITLE
Please add an option to deactivate "force https"

### ISSUE THREAD

**Issue by SkeeeRoy** [Piwigo/Piwigo-Mobile#230]
Hi,

one of the last update of the app forces a https connexion.
My site does not have. It's pretty annoying to wait the message "try without".

Plus my children who can't read yet won't be able to access the gallery with their photos anymore.

Can't you add a opt-out option to directly connect in http for those who don't have https? Or to "force http"? Or whatever you want that would allow a direct access to http gallery?

Thank you and congrats for the app.

**Comment by plegall** [comment]
It's great to have a connection "secure by default", but I agree the current UI is not great for Piwigo behind an HTTP connection that will never be on HTTPS. It can make completely sense to be in HTTP, for an intranet for example. I don't know what would be the best user interface here, but the current one is annoying for "only HTTP".

**Comment by SkeeeRoy** [comment]
Super!
I don't know if currently the delay before the question is a timeout or a high number of trials, but then please don't set it too long/high in this case before automatically switching the protocole.

**Comment by EddyLB** [comment]
Can you please tell me how long it takes to be asked for a HTTP trial with your server ?

**Comment by EddyLB** [comment]
It takes 30 seconds because your server times out instead of returning an error to a request it cannot handle. If the server replies an error, the app switches to HTTP immediately.

**Comment by SkeeeRoy** [comment]
Thank you for the explanation. Then do as you think the best, if 30 sec of timeout are necessary and/or if in the future you let people choose the protocole again... :)
