### ISSUE TITLE
Community plugin — Fewer admin notifications

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#231]
Hi @EddyLB 

With plugin Community, the iOS app calls API method `community.images.uploadCompleted` after each image uploaded. This API method was not designed this way: you can call it only once you have upload your whole batch.

For example, you have 10 photos in the queue, you only call this method once the 10 photos are uploaded. This way, the admins only get one notification email (which is already a lot, if you consider several batch in a day and several users simultaneously, we're working on it)

**Comment by EddyLB** [comment]
After a number of tries, calling the method when the app is going to enter background does not work as reliably as needed. So the app will call the method each time it finishes a series of uploads successfully or not).
