### ISSUE TITLE
Piwigo App not working on site.

### ISSUE THREAD

**Issue by MasterSergeantD** [Piwigo/Piwigo-Mobile#233]
My site is set up http.  When I try to login to the app, it attempts https: then asks to try http.  At that point the app hangs at the login screen with no error message appearing.  It's almost as if the try button is set the same as the dismiss button.

**Comment by EddyLB** [comment]
Yes, the app forces https. If the server is set properly, the app receives an error message and switches immediately to http. 

In the case where the server does not answer, the app switches automatically to http after a timeout of 30s. That duration will be reduced in the next release (presently in beta phase). The app will also remember to use http until the server address is re-edited. If you wish to test it, send me an email.

**Comment by EddyLB** [comment]
The version 2.2 will soon be released on the App Store.
