### ISSUE TITLE
show thumbnail when editing a photo

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#235]
I'm running Piwigo iOS 2.2. When you edit a photo, you no longer see it. Would it be possible to add the thumbnail before the form?

![piwigo-ios-edit-photo](https://user-images.githubusercontent.com/9326959/42891151-f14d5f52-8aae-11e8-920d-4b6a0a43a234.png)

**Comment by sebbi3** [comment]
Yes, our users have requested if it will be possible to add a thumbnail when editing the photos so they can see what they are editing. Something simple like click to enlarge so they can see what the image is and if they selected the right one.
