### ISSUE TITLE
Insecure after login to Piwigo mobile iOS

### ISSUE THREAD

**Issue by laddo618** [Piwigo/Piwigo-Mobile#243]
I am having issues viewing photos and albums in piwigo.
I have secured the site with LetsEncrypt SSL cert and the site is secure until I login as Administrator.
If I try to use the force https plugin i receive a message stating 'Your hosting server does not support HTTPS, a SSL certificate is required. Plugin activation is disabled.'
The cert is fine and the home site is completely secure. It is only Piwigo that is showing as inscure after I login as , say Administrator.
I cannot view any pictures at all using the mobile iOS now.
Can you please assist me with getting this working. I am happy to take this privavtely and allow access to the site if required.
Many thanks

**Comment by EddyLB** [comment]
Hi @laddo618 
The easiest is probably to send me by email the URL of your website (available on my profile). I will have a look and will come back to you.
All the best

**Comment by EddyLB** [comment]
Can you please tell us if this issue is fixed ?

**Comment by laddo618** [comment]
This is now resolved by the latest release of the mobile app v2.2.3
My photos were using :80 in the URL and failing to load due to ssl requirement
The app now manages this automatically by replacing the base URL of the images.
