### ISSUE TITLE
Image downloaded is not the right image

### ISSUE THREAD

**Issue by yarez0** [Piwigo/Piwigo-Mobile#249]
Hi, 

when I want to download image from my library, sometimes the image downloaded is not the one I choose

iOS 12 beta (last)
Piwigo 2.2.3 (134)

**Comment by yarez0** [comment]
Hi Eddy

Just notice on iPad version something strange. 

Sort order Setting is set to creation date recent -> ancient

An album sort me photos and videos in order, tap to see one ok, back, tap again, ok. 

Tap on another picture or video, ko, not the good one displayed, when back, the sort order change, appear to be random but the image previously displayed is now where I tapped. Tap again on the image ok, back and tap again ok. 

Tap on another image same problem, photos "moves" but not all time, it is random. 

Just test on iPhone version, all ok in the beginning but when I put it in lanscape random move occured. Back to portrait also random move. 

iPad was in lanscape from the beginning. 

Sort order set to title A -> Z correct the problem in both portrait and lanscape (iPhone and iPad). 

Don't know if my download problem and this one are linked. For the record I updated php and do maintenance database yesterday and all download are ok for now, can't reproduce the bug.

**Comment by yarez0** [comment]
Bug still here. Sort by name A-Z, the photo downloaded is the photo after the random move so the problem is the sorting / displaying order

**Comment by EddyLB** [comment]
Thank you for your testing. 
Can you please tell me what are your cache settings?

**Comment by yarez0** [comment]
iPhone (iOS 12 bêta public + piwigo 2.2.3 bêta & server 2.9.4 up2date)

> Download all ON
> Disk 21,8/80
> Memory 0,6/80

iPad  (iOS 12 bêta dev + piwigo 2.2.3 official)
> ON
> 43,8/80
> 47/80

**Comment by EddyLB** [comment]
@yarez0 , a new beta version is now available for TestFlight testing. Could you please test it and tell me whether this issue is fixed? If you are not already registered with TestFlight, just tell me.

**Comment by yarez0** [comment]
Hi Eddy sorry I’m late. All seems ok now thanks
