### ISSUE TITLE
Losing server settings ?

### ISSUE THREAD

**Issue by jessie-github** [Piwigo/Piwigo-Mobile#278]
Hello,

I am on TestFlight and lately it seems that the app is sometimes losing the server setttings.
My Piwigo server has a https URL and if I enter directly https://piwigo.example.com then everything works fine for a while.
Then under some conditions (that I have yet to identify), I suddenly have HTTP error code 405 (Method not allowed) thrown around and couldn't access the gallery anymore.
The server settings address doesn't show if it is http/https (only "piwigo.example.com"), so I disconnect and reconnect using explicitly https://piwigo.example.com and after that it works.

I will update the issue if I manage to clearly reproduce it.

**Comment by EddyLB** [comment]
Thank you for reporting this issue. 

To know if the app switched to http, open the Preferences section and check if there is a message at the top telling that the connection is not secured. 

Then logout and see whether it is written that the connection is not secured at the bottom of the login page. In the absence of this message, tap Login without typing the address. 

Then please let me know what happened and what you were doing with the app right before you encounter the issue to help me investigate this issue. 

Many thanks in advance. 



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EddyLB** [comment]
I could finally reproduce the issue. This happens when the iOS device switches to another network e.g. Wi-Fi => 4G and the app fails checking the session status without informing the user.

**Comment by jessie-github** [comment]
Hello,

It finally happened again recently. Indeed the app switched to http (not secured).
I haven't done anything with the app before, it's just that I haven't used it for a long time (several weeks).
It was with version 2.3.1.

**Comment by EddyLB** [comment]
Hi Jessie,
A beta version that should fix this issue is now available for testing. Do you want to test it with TestFlight or simply prefer to wait for the final release ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessie-github** [comment]
Yes I updated to the new version. But as I don't know how to reproduce the issue, I cannot yet confirmed  that the issue is really fixed.
I just know that it usually happen after I don't use the app for a long time.
I'll keep an eye on it.

**Comment by EddyLB** [comment]
Thank you ;-)

**Comment by nuccch** [comment]
I reproduce this problem on v2.12.4 .
reprocuce steps: set the default root album as custom album.

**Comment by EddyLB** [comment]
I suspect that the problem you report is the one described in #521 which will be fixed soon in v2.12.5.
