### ISSUE TITLE
Timeline view?

### ISSUE THREAD

**Issue by helmut72** [Piwigo/Piwigo-Mobile#290]
**Is your feature request related to a problem? Please describe.**
Piwigo Mobile app for iOS get some nice improvements in the last months, but I always miss a timeline view like on the original Photos app.

**Describe the solution you'd like**
1. an option/switch-button to switch from album view to timeline view in the current album + sub-albums
2. an option in the preferences to have timeline view enabled by default for a specific album (+ sub-albums). For example album "Imported" always use timeline view as default, which also includes sub-albums like "Imported/iPhone", "Imported/iPad", "Imported/GoPro" ...

**Comment by EddyLB** [comment]
I have coded a timeline view by day for easing the selection of local images before upload. It will be deployed with the next release 2.3.2. I will consider the option you propose in a near-future version.

**Comment by EddyLB** [comment]
Hi @helmut72 ,
Have you tested the version 2.3.2? Is the timeline view presented for selecting images to upload looks like what you have in mind?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by helmut72** [comment]
Hi @EddyLB sorry for the late answer.

yes, **exactly** what I have in mind! I also like your option to change sorting! Great!

**Comment by mfauvain** [comment]
Hi, also interested in the timeline view for all photos (like apple photos app). Running app v2.4.8 but don't see the option.

**Comment by EddyLB** [comment]
Hi @mfauvain 
I actually work on the upload management and as you can see below I have prepared an option for sorting Photo Library photos by month, week and day. Would this option answer your demand?

<img width="282" alt="Screen-Shot - iPhone-11-Pro@2x" src="https://user-images.githubusercontent.com/7103032/85979867-9b269a80-b9e1-11ea-854d-409245bbabfc.png">

**Comment by mfauvain** [comment]
That would be perfect yes

**Comment by mfauvain** [comment]
I saw a piwigo ios app today but timeline view is not there. Can I help with beta testing?

**Comment by EddyLB** [comment]
Hi @mfauvain ,.
For the timeline view, please be patient. It will come later because we must first finalise background uploading and then introduce a new cache management to not duplicate the work (we are re-codingthe app from scratch in Swift). 
Anyway, we will be pleased to welcome you as a beta tester at anytime. Just [send me an email](mailto:ios@piwigo.org) to become beta tester.

**Comment by mfauvain** [comment]
understood, many thx

**Comment by darrepac** [comment]
I am looking into a new hosting for my photos following google announce.
Question:
- this issue is still open, does it mean that the timeline view is not implemented in the ios app?
- I do not find a timeline view in the web/http side, do you confirm that such view doesn't exist?

thx

**Comment by EddyLB** [comment]
Hi @darrepac 

- A timeline view has been implemented in the version 2.5.1 of the iOS app for easing the selection of photos to upload (see above). Version 2.5.2 will very soon bring background uploading and a number of fixes. We have completely rewritten this part of the app in Swift to take advantage of modern iOS features.
- The implementation of a timeline in album views will be coded when we shall re-code this part of the app, i.e. after the addition of the camera in the upload management.
- The web interface of Piwigo allows you to display photos in a calendar view (menu "Discover / Calendar"), by week or month.

**Comment by martinhrpi** [comment]
A timeline view like iOS Photos would be the main reason for me to use Piwigo (and maybe a cleaner Design) since Synology Made a bad New App and Google isn‘t free anymore.

**Comment by martinhrpi** [comment]
A timeline view like iOS Photos would be the main reason for me to use Piwigo (and maybe a cleaner Design) since Synology Made a bad New App and Google isn‘t free anymore.

**Comment by darrepac** [comment]
Is there any update on this feature request?

**Comment by EddyLB** [comment]
Like you, I wait impatiently for a timeline view.

We are programming the automation of the uploads, an option awaited by many users which should be deployed in a few weeks. We shall then start rewriting the presentation of photo albums. This will be a huge job because we would like to bring offline capabilities too. We code outside working hours to keep the app free so please be patient. Thank you.

**Comment by darrepac** [comment]
Any news on this topic?

**Comment by helmut72** [comment]
Some weeks ago I was also thinking to ask after one year. But as long as my Synology works, I use Synology Photos. Not perfect and I need specific hardware, but all basic features are there including timeline view with easy ui on mobile app and web ui. Can wait for another 1-2 years.

**Comment by EddyLB** [comment]
The presentation of albums/images is rewritten and we now start preparing the offline browsing option. The timeline view will come right after because it will be much easier to implement afterwards.
