### ISSUE TITLE
http error 501 and 502 while uploading images from iphone

### ISSUE THREAD

**Issue by brunobydesign** [Piwigo/Piwigo-Mobile#292]
From the apache log :

POST /albums/ws.php?format=json&method=smartpocket.images.logHistory HTTP/1.1" 501

POST /albums/ws.php?format=json&method=pwg.images.upload HTTP/1.1" 502

**Comment by EddyLB** [comment]
Hi @brunobydesign 
- The iOS app never uses a `smartpocket.images.logHistory` method (not listed [here](http://piwigo.org/demo/tools/ws.htm)). So the error 501 cannot be generated by the iOS app.
- As for the request `pwg.images.upload`, the server returns the error 502, which means that the server was acting as a gateway or proxy and received an invalid response from the upstream server. I therefore can only invite you to look at the logs of the upstream server.

**Comment by brunobydesign** [comment]
Thanks for your answer,  Eddy, i'll check further ont this issue

**Comment by EddyLB** [comment]
Any news?

**Comment by EddyLB** [comment]
Without answer, I guess the problem was due to some server configuration problem and I close this issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brunobydesign** [comment]
Hi, it turns out the user was trying to continue to use his phone (sending mails, using social apps, etc...) while uploading a bunch of photos (from several dozens up to 200). He acknowlegded later that he learned from this to not do anything else with his phone during piwigo uploads. So, you app works fine... as long as the user is not a phone addict making hundredths of photos compulsively :) 
More seriously, if you know how to make the upload more resilient to multitasking, it might worth try to do it, it would enhance the UX for some people.

Thanks and regards
Bruno

**Comment by EddyLB** [comment]
Thank you for the explanations. 
You are right, the upload method needs to be redesigned. This is in the job list. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EddyLB** [comment]
See #31 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
