### ISSUE TITLE
Offline Capability

### ISSUE THREAD

**Issue by m0urs** [Piwigo/Piwigo-Mobile#297]
I did not find any option for it so I guess this is currently not possible:

I would like to haven offline capability in the iOS and Android app so that I can download selected albums and show it on my device without beeing online.

I first thought, that I might do that by increasing the cache size to maximum and display all photos in an album while beeing online. However, as soon as I go offline later, I am unable to display the cached data as I need to login first into the app which is not possible if I am offline.

So I would be very happy to see such a functionality in a future version.

**Comment by EddyLB** [comment]
We have started working on this functionality which would greatly improved users’ experience. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EddyLB** [comment]
Cache management changed (see ba42752546c1722823676342e0719d62f0687ef0)

**Comment by EddyLB** [comment]
Not fully done yet…

**Comment by martinhrpi** [comment]
Is there an update on this feature?

**Comment by EddyLB** [comment]
There is still a lot to do but we've made progress. We progressively change the way the app collects and stored data with offline capability in mind.

**Comment by f1yankees** [comment]
Seems like this is underway but wanted to +1 as this would be a **great** feature

**Comment by WhatIsThisAllAboutSilly** [comment]
+1 here too!

**Comment by bfd69** [comment]
I would love to have this functionality !
+1

**Comment by andsofine** [comment]
any updates?

**Comment by EddyLB** [comment]
Today, the tags, the locations of images and all data related to uploads are stored persistently. What is not visible is that we have now converted 80% of the code to Swift for improving the stability, taking advantage of modern methods and getting rid of old third-party libraries. This work will facilitate the adoption of new iOS libraries and the implementation of a persistent storage of album data, image data and thumbnails (refreshed in the background).

We shall store in persistent memory album data (≈1 kB/album), image data (≈4 kB/image), thumbnails (≈250 kB/image) and if possible images of a resolution matching the device screen size. For 500 albums containing 70 images in average, this amounts to 500 x (1 + 70 x (4 + 250)) ≈ 8.5 GB for data and thumbnails only. So we foresee to fill the cache in decreasing priority order with: the album data, the album thumbnails, the image data, the image thumbnails, and finally with higher-resolution images and videos. Of course, we shall continue cache the shared images to speed up the app usage.

Does that make sense for you? How much space are you ready to provide to Piwigo for the cache? I ask the question to anyone following this issue.

**Comment by bfd69** [comment]
Sounds very promising !

Envoyé de mon iPhone

Le 15 mai 2022 à 13:33, Eddy Lelièvre-Berna ***@***.***> a écrit :

﻿

Today, the tags, the locations of images and all data related to uploads are stored persistently. What is not visible is that we have now converted 80% of the code to Swift for improving the stability, taking advantage of modern methods and getting rid of old third-party libraries. This work will facilitate the adoption of new iOS libraries and the implementation of a persistent storage of album data, image data and thumbnails (refreshed in the background).

We shall store in persistent memory album data (≈1 kB/album), image data (≈4 kB/image), thumbnails (≈250 kB/image) and if possible images of a resolution matching the device screen size. For 500 albums containing 70 images in average, this amounts to 500 x (1 + 70 x (4 + 250)) ≈ 8.5 GB for data and thumbnails only. So we foresee to fill the cache in decreasing priority order with: the album data, the album thumbnails, the image data, the image thumbnails, and finally with higher-resolution images and videos. Of course, we shall continue cache the shared images to speed up the app usage.

Does that make sense for you? How much space are you ready to provide to Piwigo for the cache? I ask the question to anyone following this issue.

**Comment by martinhrpi** [comment]
I agree, would be perfect!

Maybe you could let the User deside on the size of the local copy (Original/2MP/3MP/...)

iPhones are now standard 128GB, mine is 256 for years now, so...

My family and I use Synology Photos now and cache is set to infinite.

**Comment by WhatIsThisAllAboutSilly** [comment]
> How much space are you ready to provide to Piwigo for the cache? I ask the question to anyone following this issue.

As much as is required! I have a library adding up to about 300k of images, caching as many of them as possible would be useful, even if it takes up 50GB or more.

**Comment by YZirkind** [comment]
Would it be possible to let the size of the cache be configurable by the user?

**Comment by EddyLB** [comment]
Yes, the size will be configurable. We may even allow users to clear the different caches individually e.g. to delete high-res images only or videos only

**Comment by benjaminchodroff** [comment]
Super excited to see this feature (I believe?) working in the 3.0 beta! Great work.

**Comment by EddyLB** [comment]
Yes, the version 3 should definitively bring this feature (assuming album data are in cache of course).
