### ISSUE TITLE
Upload of iOS video without required ffmepg

### ISSUE THREAD

**Issue by pojny** [Piwigo/Piwigo-Mobile#303]
Most of basic hoster don't provide ffmpeg support.
In that case, video upload works fine whith standard synchronise on the gallery, but not whith piwigo mobile application.

that would be great if it were possible to upload the video whitout creating thumbnail and so without require ffmpeg.

Maybe it is possible to use a generic thumbnail in that case.
Or the user have to manually specify a thumbnail to use for the video.

**Comment by EddyLB** [comment]
Piwigo-Mobile can upload videos recorded with iOS devices even when `ffmpeg` is not installed. Please have a look at the [wiki page](https://github.com/Piwigo/Piwigo-Mobile/wiki/Upload-and-download-videos) I have updated to help users configure their servers.

**Comment by pojny** [comment]
Thanks for your response, sorry my mistake
