### ISSUE TITLE
Background Image Uploading

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#31]
Be able to background the app and have the images still upload.

**Comment by SpencerBaker** [comment]
I instead implemented that the app wont background when you're uploading or downloading an image.

**Comment by EddyLB** [comment]
It would be preferable to code the batch manager (issue #346) before coding the background uploader.

**Comment by EddyLB** [comment]
After detailed investigation and testing, it is not possible to upload images in the background with the current API methods:

- The method `pwg.images.addSimple` employs the `multipart/form-data` encoding for uploading a file but is limited to a single URL request (hence its name), which limits the size of the uploaded file.
- The method `pwg.images.add` employs the standard `application/x-www-form-urlencoded` encoding for uploading a file in combination with `pwg.images.addChunk` which must have been called (several times) before. This is very inefficient when uploading big files (the amount of data uploaded per request is very limited) and this does not allow to perform asynchronous file uploads (required by the iOS BackgroundTasks framework).
- The method `pwg.images.addFile` looks to be similar to `pwg.images.add` without the capability to set image parameters.
- The method `pwg.images.upload` employs the `multipart/form-data` encoding. For uploading big files, it is called several times but from my tests the chunks have to be sent in ascending order. If not, the chunks are not properly recombined. This method therefore does not allow to perform asynchronous file uploads either.

I have therefore implemented a technique where upload requests are stored in persistent memory and executed whenever possible, i.e. when the app is in the foreground. To implement background uploading, i.e. when the app is not in foreground on the iOS device (sleeping or fully inactive), we need a new API method like the one described here: https://github.com/Piwigo/Piwigo/issues/1203.

**Comment by EddyLB** [comment]
Should check each chunk file with MD5 checksum
