### ISSUE TITLE
Search Ability

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#32]
Be able to search for an image by name.

**Comment by SpencerBaker** [comment]
Search by file name and image title.

**Comment by SpencerBaker** [comment]
Search whole app and in current album.

**Comment by EddyLB** [comment]
@plegall, I see that the `pwg.images.search` method requires a query and some limits which will I guess filter the result (hits, date created, etc.). Can you please tell me how I can implement a search tool similar to the one of the web interface from this method ?

**Comment by EddyLB** [comment]
Search by date, hit, rate and max level

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
