### ISSUE TITLE
[BUG] iOS app gives timeout message when uploading, but image is uploaded

### ISSUE THREAD

**Issue by paraviz02** [Piwigo/Piwigo-Mobile#323]
**Describe the bug and how to reproduce**
Open iOS application, log in, select an album and start to upload a single image.  After a period of time, it will say that the upload failed because of a timeout.  But the photo is available.

1. See above -- basic iOS upload process.

**Expected behavior**
Expected behavior would be to have an upload successful message.

**What did you do already**
 - Search whether a similar issue is already reported?  Yes
 - Check for known workarounds in the issue tracker?  Yes
 - Did you check with guest login?  No - guests not allowed
 - Did you try to reproduce it with https://www.piwigo.org/demo/ ?  Not yet
 - Upgraded iOS app and Piwigo software

**Screenshots**
![Image-1](https://user-images.githubusercontent.com/6978717/61976655-2eb94500-afa1-11e9-8a92-651c7ac575c8.jpg)
![Image-1](https://user-images.githubusercontent.com/6978717/61976664-3842ad00-afa1-11e9-8654-3c386af3386b.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 10.4
 - App version 2.9.5

**Additional context**
 - I can message site location upon request
 - Active plugins are: LocalFiles Editor, RV Maps&Earth, Take A Tour of Your Piwigo, and VideoJS

**Comment by EddyLB** [comment]
Hi @paraviz02 
Could you please provide me with a temporary read/right access to a test album so that I can reproduce the issue? You can contact me directly from the iOS app from the Preferences page (Information section / Contact Us).

**Comment by EddyLB** [comment]
Solved after exchanging emails with @paraviz02 — Was due to DNS issue behind NAT.
