### ISSUE TITLE
Decode HTML encoded titles, descriptions…

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#324]
In some cases, users copy/paste texts from editors, etc. which are HTML encoded. To display them properly, the iOS app should automatically perform HTML character decoding.

**Comment by EddyLB** [comment]
However, users may paste text encoded in different ways which are not straightforward to identify (HTML, XML, UTF-8, ISO-8859-1, etc.), especially when the declaration is not provided. The user may even paste texts encoded differently in the same field without declarations. So users should decode the encoded text they pasted.

**Comment by miklosbagi** [comment]
☝🏻 that explains a lot of what I've been scratching my head about, thanks!
