### ISSUE TITLE
Search by Tags

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#33]
Have a list of tags you can select and get back a list of images containing those tags.

**Comment by EddyLB** [comment]
While adding this, it would be great to add compatibility with the Tag Groups extension.

**Comment by yarez0** [comment]
it would be great to have this !

**Comment by EddyLB** [comment]
The app cannot presently retrieve the name of the group into which a tag belongs to. So it won't be able to present tags sorted by groups until https://github.com/Piwigo/Piwigo/issues/1043 is closed.

**Comment by EddyLB** [comment]
I split this issue and keep here the original idea to display tagged photos as proposed in the Discover menu of the web interface. The compatibility with Tag Groups is now identified as issue #315.
