### ISSUE TITLE
[BUG] Not every tagged images are shown

### ISSUE THREAD

**Issue by voriondev** [Piwigo/Piwigo-Mobile#336]
**Describe the bug and how to reproduce**
Only X photos are shown when getting all the photos using a tag.
If you choosed to have 3 photos per line, 18 photos only will be shown up.
If you choose to have 6 photos per line, 66 photos will show up.

1. Go to 'Sorting'
2. Click on 'Tags'
3. Scroll down to whatever tags you wanna get the photos from.

**Expected behavior**
I guess the expected behavior is to show up every tagged photo..

**Screenshots**
![Screenshot1](https://sandbox.piwigo.com/i?/uploads/4/y/1/4y1zzhnrnw//2019/09/12/20190912104546-11419957-xl.png)

![Screenshot2](https://sandbox.piwigo.com/i?/uploads/4/y/1/4y1zzhnrnw//2019/09/12/20190912104549-a8e48919-xl.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S / iPhone 8 Plus / iPhone X
 - OS: iOS 12.4.1 / iOS 12.4 / iOS 13.1
 - App version: 2.4.2

**Additional context**
 - Used hannah.piwigo.com to try out this function.

**Comment by EddyLB** [comment]
Thanks for having reported this bug.
