### ISSUE TITLE
[BUG] App stuck when server cannot return image data or image thumbnail

### ISSUE THREAD

**Issue by hencisk** [Piwigo/Piwigo-Mobile#340]
No content (items) displayed for some albums from mobile app. There is only message given "No albums in your Piwigo yet. You may pull down to refresh or re-logon". Content for these albums is normally visible from web. Unfortunately haven't figured out, which items or for what reasons are causing that, but could be albums containing some or some type of videos. Can grant access to my gallery for troubleshooting, if needed.
Only thing I have figure out is couple of errors in apache error log, when accessing album from mobile:

`
[Mon Sep 30 20:31:33.927371 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927459 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927507 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927552 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927596 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927658 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
[Mon Sep 30 20:31:33.927710 2019] [php7:notice] [pid 14086:tid 140226751022848] [client 212.3.197.134:55522] PHP Notice:  getimagesize(): Read error! in /var/www/mysite/html/include/derivative.inc.php on line 159
`

These are not there accessing it via Web.
Do not find any similar issues reported. And happens with whatever user (admin or regular)

**Smartphone (please complete the following information):**
 - Device: [e.g. IPhone X]
 - OS: [e.g. iOS 12.4]
 - App version [e.g. 2.4.3]

**Comment by hencisk** [comment]
Just did additional testing. Seems the issue is really related to video files or there was one short video file with probably no thumbnail generated. Deleted that one and album is normally opening. It would be perfect, if this exception could be handled displaying some default icon, like this in piwigo web or skipping item at all. Can send this short video file, if needed, for testing (
![icon](https://user-images.githubusercontent.com/54588681/65906470-54acfc80-e3cb-11e9-8135-67def32ec916.JPG)

**Comment by EddyLB** [comment]
There is indeed an issue preventing the successful download of videos in version 2.4.3. A new version 2.4.4 has been submitted to Apple today for correcting this problem.
Please come back here later this week after updating the app and tell me if the problem is solved. Sorry for the inconvenience.

**Comment by hencisk** [comment]
This actually isn't directly related to video problem, but seems whatever problematic item. Was uploading today bunch of different content to Piwigo album from mobile app. At same state it crashed and closed. Probably with this one had single photo broken. And having such situation, no album content is loaded into Piwigo mobile app. It is shown, like empty album. Fixed it from web, where you can still normally open the album and found out broken picture from thumbnail, where only half of picture was shown. After deleted that, album load normally also in mobile. So it would be great, if such exceptional case wouldn't affect displaying of rest of album content.

**Comment by EddyLB** [comment]
Thank you for reporting this issue.

**Comment by EddyLB** [comment]
Version 3.0 filters error messages returned by the Piwigo server before/after the expected JSON data.
