### ISSUE TITLE
[BUG] iOS 13 dark mode on login page

### ISSUE THREAD

**Issue by voriondev** [Piwigo/Piwigo-Mobile#343]
**Describe the bug and how to reproduce**
Using iOS 13's brand new dark mode, the fields placeholders are not really readable anymore.

1. Try logging in on your Piwigo :)

**Screenshots**
This is what I see in **dark mode**:

![DARKMODE](https://sandbox.piwigo.com/i?/uploads/4/y/1/4y1zzhnrnw//2019/10/11/20191011151652-39181bba-la.png)

and what I see in **light mode**:

![LIGHTMODE](https://sandbox.piwigo.com/i?/uploads/4/y/1/4y1zzhnrnw//2019/10/11/20191011151653-06f915cc-la.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus & iPhone X
 - OS: iOS 13.1.2 (for both)
 - App version: 2.4.4 (release 230)

**Comment by voriondev** [comment]
Hello @EddyLB ,

To be honest I did not do anything special.. I just installed the Piwigo app from the store (with iOS 13 dark mode enabled), and launched it. Whenever I kill the app from the switcher and run it, if the dark mode is enabled the placeholders are not visible..

I did the same thing on my iPhone X and the same issue shown up.

**Comment by EddyLB** [comment]
Thank you for this additional information. 

I can now reproduce the issue which appears when there is no data entered. I will fix the colour of the placeholders in the next release. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
