### ISSUE TITLE
Lock the app with a pin or Touch ID or Face ID

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#348]
On the App Store, some users have asked for an option to lock the app with a pin or Touch ID or Face ID. This would indeed help them protect their favorite photo library.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihatemyisp** [comment]
Has there been any progress on this?

**Comment by EddyLB** [comment]
We've made some progress but they are not visible. We have modified some of the code managing logins and translated a lot of the old Objective-C code into Swift so that we can adopt modern APIs. Thank you for your patience.
