### ISSUE TITLE
Rename selection of files / add prefix to filenames

### ISSUE THREAD

**Issue by unnilennium** [Piwigo/Piwigo-Mobile#350]
**Is your feature request related to a problem? Please describe.**
Most of us are using the same phone in the family, and they all use the same way of naming the files 

As a result when we upload to the same album , we could hit the situation where two peoples will upload different photos with the same name.

IMG_2271.JPEG

**Describe the solution you'd like**
To avoid this I suggest to apply a global filter on all uploaded files to rename them with a special string dedicated to the phone we use, and to simply use a field in the parameter if we want to use this function. This could be to replace the standard string or add a string to the filename:

JPP_IMG_2271.JPEG
Or
JPP_2271.JPEG

**Comment by EddyLB** [comment]
Thanks for the suggestion. 
I see two different approaches here:
- Provide a new setting in the Preferences / Upload section allowing to add a prefix to image file names
- Provide a command allowing to change the file names of a selection of images. 

Agreed? I guess that both would be welcome. 
Please note that file names differ from image titles which can be set separately. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unnilennium** [comment]
both would be welcomed, while I will see the fact that it is set one time for all in the preferences an easy approach and allow me not to forget or change the string every time.
However, having a reminder that the string will be enforced before upload would be great ! (similarly but another bug, would be great to know if the delete after upload is enforced before starting the upload)

thanks !

**Comment by EddyLB** [comment]
Ok, good point. The app will therefore provide an additional option in Preferences to add a (default) prefix to file names before upload.

I also open an issue with regard to the upload page which should inform and also allow users to change the default settings before uploading a series of photos.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
