### ISSUE TITLE
[BUG] Disable download not effective

### ISSUE THREAD

**Issue by PhotosESM** [Piwigo/Piwigo-Mobile#371]
When download is disabled on the website it's still possible to download in the app.

**Comment by EddyLB** [comment]
Can you please tell me how you disabled downloads?

**Comment by PhotosESM** [comment]
Menu Configuration>Affichage : Activer l'icône "Télécharger ce fichier"

**Comment by EddyLB** [comment]
If you disable the access to high-resolution photos on your server, the iOS app will only be able to download low-resolution images with watermark. Would that solution answer your needs?
