### ISSUE TITLE
Error Message when trying to delete the first letter of server url

### ISSUE THREAD

**Issue by YasserAntonio** [Piwigo/Piwigo-Mobile#389]
**Describe the bug and how to reproduce**
Using iPhone 6 on IOS 12.4.8 with the 2.4.8 Piwigo iOS version, when I want to change the server url I keep my finger on the delete button to delete all letter backward. Unfortunately when the I arrive to the first lette ri got an error message telling me that  that the url is not correct.

1. open the Piwigo App
2. type any letters on the url server box
3. keep your finger on delete button
4. See error when it arrived at the  first letter ( ![Image-1](https://user-images.githubusercontent.com/8104486/91646009-1bea2d00-ea4b-11ea-92f8-4427706ac5ae.jpg))

**Expected behavior**
Delete the url server without any unnecessary error message

**What did you do already**
 - Search whether a similar issue is already reported : done
 - Check for known workarounds in the issue tracker : done
 - Did you try to reproduce it with https://www.piwigo.org/demo/ : impossible to reproduce

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 12.4.8
 - App version 2.4.8(269)

**Comment by EddyLB** [comment]
Can you please check that this bug is fixed in the version 2.5 deployed yesterday on the App Store?

**Comment by YasserAntonio** [comment]
It's solved !  Thanks
