### ISSUE TITLE
iOS - movie upload failure

### ISSUE THREAD

**Issue by windship** [Piwigo/Piwigo-Mobile#405]
![IMG_4568](https://user-images.githubusercontent.com/24471913/95654649-5d86f100-0b3c-11eb-83c6-f92dd34a6b9a.PNG)

I installed Piwigo on my Macmini and it seems work well for photos, but only movie files could not uploaded from my iPhone.
When I try to upload some movie file, iOS app shows me an error like as "File format not accepted by Piwigo... Could not diget the fetched data." 

What is this error means and how to fix this? 
Any idea or advices will be appreciated!

**Comment by EddyLB** [comment]
Hi @windship ,
Have you looked at [this page](https://github.com/Piwigo/Piwigo-Mobile/wiki/Upload-and-download-videos) of the Wiki?
Cheers

**Comment by windship** [comment]
Hi Eddy, 

Thank you for your advice. I didn't know that plugins necessary for the video upload.
I tried and it works well. 

Thank you very much!!!

**Comment by Phil353556** [comment]
Hi,  I relay what @EddyLB shared (huge thanks to him!) 
- https://github.com/Piwigo/piwigo-videojs/wiki/How-to-add-videos
- https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos
It works, I tested  -  only issue found, cleanup cache on mobile to have posters displayed
