### ISSUE TITLE
[BUG] crash when selecting album for upload

### ISSUE THREAD

**Issue by exekutive** [Piwigo/Piwigo-Mobile#422]
1. Press the '+' button , then photo upload (app shows photos library with local albums)
2. Select my local album called "highlights"
3. Piwigo crashes

**What did you do already**
- tried to upload to different remote album (still crashes)
- tried to upload a different local album (no crash)

- (Did you try to reproduce it with https://www.piwigo.org/demo/ ?)
demo does not allow upload

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: 14.2
 - App version 2.5.3 (331)

**Comment by EddyLB** [comment]
I have created albums, synced albums from a Mac, etc. and  I cannot reproduce this issue with full or limited access to the Photo Library.
Can please tell me more about this album "highlights"? How was it created? How many and what type of images are stored in it? Dis you provide full or limited access to the Photo Library of your iPhone?

**Comment by exekutive** [comment]
It is an album containing 33 photos. I created it on my Mac and then dragged a bunch of my favourite photos into it. There are two HDR photos. Some are "Live".  Some were captured with a digital camera.

Piwigo app has access to "All Photos"

**Comment by exekutive** [comment]
does the app have debugging/logging?

**Comment by EddyLB** [comment]
I have now received the logs of the crash via TestFlight and I am going to try to fix this issue in the coming week.

**Comment by exekutive** [comment]
these steps no longer cause a crash in 2.5.4
Thank you.
