### ISSUE TITLE
[BUG] Unable to submit feedback

### ISSUE THREAD

**Issue by exekutive** [Piwigo/Piwigo-Mobile#423]
I think this is an issue with Apple Testflight rather than Piwigo, but you should know about it anyway.

When Piwigo crashes, I'm offered the opportunity to send feedback. However, I'm unable to add any info because the onscreen keyboard goes off the screen. This cannot be helped by phone orientation (the form is locked into portrait).

![8B5994E7-FBF2-4CE9-A429-A51D67F532E3_1_105_c](https://user-images.githubusercontent.com/4755215/102949353-f4e1bc00-447c-11eb-896d-cc78c73e6624.jpeg)

**Comment by EddyLB** [comment]
This is clearly a TestFlight app issue.
Because it seems that only registered developers can send feedback reports on the TestFlight app to Apple ([Product Feedback](https://www.apple.com/feedback/)), I did it and I close this issue as this is the only thing we can do.
