### ISSUE TITLE
Some UI streamlining

### ISSUE THREAD

**Issue by exekutive** [Piwigo/Piwigo-Mobile#424]
I would like to share my personal feelings about the UI, and how I think it could be made more intuitive.

### When manually selecting photos for upload ....

![image](https://user-images.githubusercontent.com/4755215/102952588-46417980-4484-11eb-9d43-2ee50548c2f8.png)

1.
There is a button called "Select". The first time I saw this, I thought this was the button to confirm my selection, and proceed to the next step. I lost my hand picked selection of images and had to do it all over again. I think you should call this "Select All" to make it obvious what it does. "Select all" is the wording seen on every OS I use.

2.
There is a menu button on the top right with more options. It's not obvious that it's a button you can press. The icon doesn't suggest what the button does.  Perhaps make the icon something like the familiar "hamburger" icon that most apps use
![image](https://user-images.githubusercontent.com/4755215/102950664-ee087880-447f-11eb-9537-1b2e7602f2d5.png)
(https://en.wikipedia.org/wiki/Hamburger_button)

Further, the menu contains some strange actions that shouldn't be together:

![image](https://user-images.githubusercontent.com/4755215/102952809-d8498200-4484-11eb-853e-8c908317b4db.png)

- "Select All"  Redundant. Already exists in main dialog
-  There is an option to toggle sorting between new/old. This could be implemented in the main dialog with a familiar sort icon
![image](https://user-images.githubusercontent.com/4755215/102951330-70de0300-4481-11eb-8eea-788f178cd98a.png)
- I also get an option to "Delete 2 Photos". I have no idea how these two photos were chosen, or why I should be deleting photos during an upload.

### On the home screen ...

![image](https://user-images.githubusercontent.com/4755215/102952500-28741480-4484-11eb-8815-1de8bdd0a0d1.png)

To me the menu icon looks like a button to switch to list view.  Again, I suggest changing this to the hamburger icon.

Also, the button disappears when I open an album. I think it could be persistent. Same with the settings icon.

**Comment by EddyLB** [comment]
A beta version taking most of your comments into account is now available for beta testing via TestFlight.

**Comment by exekutive** [comment]
Awesome I love it.
