### ISSUE TITLE
[BUG] unable to download original size

### ISSUE THREAD

**Issue by benjaminchodroff** [Piwigo/Piwigo-Mobile#428]
I am unable to download original sized photos using the Piwigo Mobile iOS app v2.5.3, regardless that Guests can download HD versions using the web application and regardless that the "Preview Photo File" in the app is set to "Full resolution" with a cleared cache.

 

**Steps to reproduce the behavior:**

1. Using Piwigo Mobile App 2.5.3, login to https://benchodroff.com/photos (no username/password required for guest)

2. Go into "Shanghai Chistmas 2020" album and download the first photo "ShanghaiChristmas2020-0001" by clicking the share icon, and then selecting "Save to Files"

3. Review the file size of the image by going to the "Files" application iOS, click and hold on the image, and select "info" - size 12.4MB

4. Repeat the steps using the web application to download the original file and note original size is 25.9MB: https://benchodroff.com/photos/galleries/ShanghaiChristmas2020/ShanghaiChristmas2020-0001.jpg

 

**Expected behavior**

By default, saving the image should default to download the largest available size including the original.

Ideally, it would be great to be able to download in the various supported sizes.

 

**What did you do already**

- Ensured Guest user is set to allow HD versions

- Ensured iOS Piwigo app is set to allow "Full resolution" previews (not sure if this is relevant or not)

 

 

**Smartphone (please complete the following information):**

- Device: iPhone 12 Max Pro

- OS: 14.3

- App version: 2.5.3

 

**Additional context**

- Can you please give the Site URL for the Piwigo Gallery that you tried to connect to? benchodroff.com/photos

- Which Piwigo extensions do you have installed? none should impact this... I hope!

**Comment by EddyLB** [comment]
This bug will be fixed in version 2.5.4. Before using it, please check in Settings / Photos / Share Private Metadata that the app is allowed to share private metadata "with other apps". If that is already the case, please clear the cache to force the app to download a fresh copy of the photo you want to share.

**Comment by benjaminchodroff** [comment]
Thanks, I can confirm this bug is closed in 2.5.4 if you adjust the app to share private metadata. Otherwise, the behavior reverts to sharing a compressed image. 

I really appreciate the fast fix! Happy new year.

**Comment by EddyLB** [comment]
For information, it is not possible to change the metadata (e.g. remove private data) without image recompression. If I specify lossless compression, the size of the image ShanghaiChristmas2020-0001.jpg increases from 26.5 MB to 37.4 MB and if I specify a compression ratio of 0.99, the final size is of 17.6 MB.

I have not found a quick way to determine the compression of the original image (this is not provided in the metadata) so I cannot export an image of the same size with modified metadata without searching for the appropriate compression ratio. This technique would be much too time (and battery) consuming so I kept the default compression ratio in the code.

**Comment by EddyLB** [comment]
A quick update to tell that I have discovered a technical note from Apple explaining how to create an image file containing modified metadata without recompressing the original image.

This requires a substantial recoding of the manipulation of the metadata but this will be implemented in the next release ;-)
