### ISSUE TITLE
Build issue: piwigoKit Tag+CoreDataClass.swift and Tag+CoreDataProperties.swift in wrong folder

### ISSUE THREAD

**Issue by miklosbagi** [Piwigo/Piwigo-Mobile#462]
**Describe the bug and how to reproduce**
Build fails as files included from:
- /Users/lelievre/Privé - GitHub/Piwigo-Mobile/piwigo/Data Cache/Tags Data/Tag+CoreDataProperties.swift
- /Users/lelievre/Privé - GitHub/Piwigo-Mobile/piwigo/Data Cache/Tags Data/Tag+CoreDataClass.swift

1. Git clone, checkout v2.7
2. Start Xcode
3. Build for simulator
4. Observe XCode Build Error

**Expected behavior**
These should be Relative to group and pointing to the files in ../../../piwigo/Data Cache/Tags Data/

I'll attempt to submit a PR to address this.

**Comment by EddyLB** [comment]
This is not a bug as it has no impact on the use of the app. These two files were not moved properly when creating the piwigoKit framework. I fix this problem and commit it.
