### ISSUE TITLE
Album description is not HTML decoded

### ISSUE THREAD

**Issue by miklosbagi** [Piwigo/Piwigo-Mobile#464]
**Describe the bug and how to reproduce**
Using special characters in Album description breaks the user experience in the mobile app as they don't they HTML decoded.

1. Create a new album in Piwigo and add the following description (example): "Ünnepek"
2. Save it, and open up the mobile app
3. Navigate to a view where the album is visible with its description
4. Observe that the app displays description as "\&\&Uuml;nnepek"

**Expected behavior**
Enable HTML decode to album descriptions.

**Screenshots**
<img width="230" alt="Screenshot 2021-07-31 at 12 33 33" src="https://user-images.githubusercontent.com/68903245/127737250-8f7f28e6-df9b-42a9-86f3-361aac39e61f.png">

**Smartphone (please complete the following information):**
 - Device: All iPhones and iPads
 - OS: All iOS
 - App version: 2.6.4, 2.7 beta (likely all)

**Additional details**
Please note that the same behavior is observable when viewing the Album title on the Album view screen.

**Comment by miklosbagi** [comment]
Attempted a fix but got stuck, Halp! :)

Adding a simple HTML decoder helps:
AlbumTableViewCell.m line 61

from:
```
    else {
        self.albumComment.text = self.albumData.comment;
        self.albumComment.textColor = [UIColor piwigoColorText];
    }
```

to:
```
    else {
        NSData* stringData = [self.albumData.comment dataUsingEncoding:NSUTF8StringEncoding];
        NSDictionary* options = @{NSDocumentTypeDocumentAttribute:NSHTMLTextDocumentType};
        NSAttributedString* decodedAttributedString = [[NSAttributedString alloc] initWithData:stringData options:options documentAttributes:NULL error:NULL];
        NSString* decodedString = [decodedAttributedString string];
        
        self.albumComment.text = decodedString;
        self.albumComment.textColor = [UIColor piwigoColorText];
    }
```

This seems to fix the iOS bit of the issue, well, somewhat.
Please note the "ő" character at the end of the second line in the comment (screenshot in bug description). That character is not HTML encoded, so decoding with the above method will actually lead to breaking that.

JSON received for the album in question from /ws.php?format=json&method=pwg.categories.getList looks like:

```
      {
        "id": 31,
        "name": "Események",
        "comment": "\r\n\t&Uuml;nnepek, ballag&aacute;sok, szallagavat&oacute;k, esk&uuml;vők, tejfakaszt&oacute;k, &eacute;s temet&eacute;sek\r\n",
        "permalink": null,
...
```

This is with content type ```text/plain; charset=utf-8```.

So the question is: 
- is this an iOS bug (we expect the iOS client app to decode these strings) and a web bug of inconsistent special character encoding?
- OR is this a plain web bug where we don't expect these characters to be encoded within the provided JSON?

**Comment by miklosbagi** [comment]
side note: editing that ő in the iOS app seems to fix that character (looking fine on both iOS and web).
This works until the user refreshes the content. That ő somehow seems to be ISO-8859-1 - is that possible?

**Comment by EddyLB** [comment]
Duplicate issue. See #324.
