### ISSUE TITLE
Split variables for settings about strings for better localization

### ISSUE THREAD

**Issue by miklosbagi** [Piwigo/Piwigo-Mobile#465]
**Is your feature request related to a problem? Please describe.**
Hungarian (and some other) languages are weird then it comes to plurals and singles.
For showing several albums, we use plural (so Albums), but when we say X number of albums, we use single (10 Album).

The settings / about screen uses the already defined plural strings.

**Describe the solution you'd like**
For better quality translations, I'd like to request adding additional strings for settings/about.

This impacts already existing translations, but the currently applied strings can be used as default values.

**Describe alternatives you've considered**
I reviewed if this can be done without code change, but concluded: not at present.

**Additional context**
Here's what I have in mind:

In Localizable strings/all languages:
```
// Settings - About
"settings_about_albums" = "existing language string: tabBar_albums";
"settings_about_images" = "existing language string: severalImages";
"settings_about_tags" = "existing language string: tags"
"settings_about_users" = "existing language string: settings_users";
"settings_about_groups" = "existing language string: settings_groups";
"settings_about_comments" = "existing language string: editImageDetails_comments";
```

in settingsViewController.swift/SettingsSection.about.rawValue case:

```
        case SettingsSection.about.rawValue:
            if nberImages.count > 0 {
                footerLabel.text = "\(nberImages) \(NSLocalizedString("settings_about_images", comment: "Photos")), \(nberCategories) \(NSLocalizedString("settings_about_albums", comment: "Albums")), \(nberTags) \(NSLocalizedString("settings_about_tags", comment: "Tags")), \(nberUsers) \(NSLocalizedString("settings_about_users", comment: "Users")), \(nberGroups) \(NSLocalizedString("settings_about_groups", comment: "Groups")), \(nberComments) \(NSLocalizedString("settings_about_comments", comment: "Comments"))"
            }
        default:
            break
        }
```

**Comment by miklosbagi** [comment]
Proposed change: https://github.com/miklosbagi/Piwigo-Mobile/commit/2f49ffa2a549916b408ec0fc769491658e4d84b4

**Comment by EddyLB** [comment]
Hi @miklosbagi 
This is weird indeed. We should improve the translation but I do not understand your solution.

**Comment by miklosbagi** [comment]
Hi @EddyLB, 

Thanks for looking into this.

2f49ffa introduces localizable strings dedicated to the settings/about section.

In that sense, changes in detail:
- Added "settings_images", "settings_albums", "settings_tags" and "settings_comments" as new variables to all piwigo/Resources/*/Localizable.strings
- Filled those new variables up with values from "severalImages", "tabBar_albums", "severalImages", "tags", "editImageDetails_comments" for all translations
- Moved settings_users and settings_groups (refactor) into that new // Settings About block
- Updated piwigo/Settings/SettingsViewController.swift to use these new variables.

So my thinking was: adds the option to all translations to localize settings / about strings separately, while keeping the original translations out of harms way (e.g. 0 impact on other translators).
