### ISSUE TITLE
[BUG] Crash at login when no scheme provided and host is http

### ISSUE THREAD

**Issue by melis-m** [Piwigo/Piwigo-Mobile#497]
**Describe the bug and how to reproduce**
App crashes at login if no scheme specified in `url` and the host is `http` and not `https`.
I only have a local server at the moment, so not very easily testable from the outside and maybe actually the bug is not exactly that.

1. Fresh install app
2. Enter a url of a piwigo server hosted on http host, without the scheme, in my case it was `192.168.x.x:8081`
3. Click Login
4. App crashes, and whenever you open the app after that it tries to reconnect again and crashes, you have to uninstall 

**Expected behavior**
The login process should not crash

**What did you do already**
 - Search whether a similar issue is already reported? -> None found
 - Did you check with guest login? -> Doesn't change anything
 - Did you try to reproduce it with https://www.piwigo.org/demo/ ? -> works, that's why I suppose it's the fact that my server is only HTTP that causes the crash
 - Tried with the scheme, so `http://192.168.x.x:8081` -> No crash
 - Tried it on the android app just in case, it works though, no crash, it automatically adds the `http://` in front

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 15.4 beta
 - App version: 2.9.4

**Additional context**
 - Can you please give the Site URL for the Piwigo Gallery that you tried to connect to? -> Local website, so nope, sorry :\ 
 - Which Piwigo extensions do you have installed? (If you think there might be a relationship / this is not always needed.) -> None
 - Add any other context about the problem here. -> This is a completely fresh install of the app and of the server

**Comment by EddyLB** [comment]
Thank you for this report. I can now reproduce the issue.
