### ISSUE TITLE
[BUG] passwords containing '&' characters are rejected

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#498]
When using passwords containing special characters like '&' are rejected.
The password added to the HTTP body request is not percent encoded properly.

**Comment by aminecmi** [comment]
I’m having issues when logging-in. My password contains multiple « & ».

whould this be the issue ?

**Comment by EddyLB** [comment]
I believe so and we are preparing a fix.
We are sorry for the troubles.

**Comment by aminecmi** [comment]
Just tested.

working with password without « & »

Thanks !
