### ISSUE TITLE
[BUG] Download not working when $conf['original_url_protection'] = 'images'

### ISSUE THREAD

**Issue by JSAnyone** [Piwigo/Piwigo-Mobile#503]
**Describe the bug and how to reproduce**
Download a photo with the Piwigo app raises the following error:
`Request failed: bad request (400)`

1. Click on the share button in the left bottom
2. Select any option (e.g. Save to gallery)

**Expected behavior**
That the download works.

**What did you do already**
With `tcpdump` I found out that the Piwigo app wants to download the photo via the following url:
`.../piwigo/action.php?id=9020&amp%3Bpart=e`

Opening this URL in a browser gives the following text: `Invalid request - id/part`
When I open the url without `amp%3B` it works and I get the image as expected:
`.../piwigo/action.php?id=9020&part=e`

Since I don't know what the function of `amp%3B` is I don't know what to do next.

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: latest
 - App version: latest
 - Piwigo version: latest

**Comment by EddyLB** [comment]
Hi @JSAnyone 

`&amp%3B` should be `&amp;` which is the character `&` in HTML. 

The iOS app downloads the image/video before sharing it and the URL used to download the file is generally something like `https://my.piwigo.domain.net/upload/2022/01/24/20220113221744-bd569f9a.jpg`. Why is your Piwigo server using action.php? Have you installed a plugin redirecting the downloads? I would like to reproduce the issue.

**Comment by JSAnyone** [comment]
Hi,

**Comment by JSAnyone** [comment]
Hi,
I really don’t know why my Piwigo server is using action.php, I thought this is a normale behavior. 
I don’t think that any of my plugins is redirecting the downloads:
![Uploading 7F335203-F243-4759-9947-CB9DEA7C5829.jpeg…]()

**Comment by EddyLB** [comment]
Thank you for the list of plugins you are using. Would it be possible to create a test album, put an image in it and create an account only having access to this album so that we can investigate the issue? This would help us very much.

**Comment by JSAnyone** [comment]
I’ve send you the credentials via email!

**Comment by EddyLB** [comment]
Thank you!

**Comment by EddyLB** [comment]
Only the XLarge, XXLarge and full resolution images have URLs including `action.php`. The server sends URLs  to the iOS app in the incorrect format: `https://my.piwigo.domain.net/action.php?id=9712&amp;part=e`. And as you said, the correct URL should be `https://my.piwigo.domain.net/action.php?id=9712&part=e`.

I am going to try to identify the origin of the issue in the server app or plugin at the origin of this issue and will also see whether it is feasible to correct such URLs in the iOS app.

**Comment by EddyLB** [comment]
After some investigation, I guess that you use `$conf['original_url_protection'] = 'images';` in your Piwigo configuration. This forces Piwigo to hide the URLs of images and explains why URLs are of the type `…/action.php?id=9712&part=e`.

**Comment by JSAnyone** [comment]
That's it! So yes, I'm using this config parameter.
But does that mean that I have to disable this option to be able to download pictures with the App?

**Comment by EddyLB** [comment]
Until we fix the issue, yes.
I am going to report this issue to the Piwigo team and add a patch to the iOS app so that you can re-enable it quickly.

**Comment by JSAnyone** [comment]
Thanks!
