### ISSUE TITLE
Too many thumbnails per row (too small)

### ISSUE THREAD

**Issue by pyRobShrk** [Piwigo/Piwigo-Mobile#508]
I resized some of the image sizes on my piwigo server, and now the app keeps changing the Number/Row slider to have a minimum value of 8 and maximum of 16. I like it with 3 or 4, as this is on an iPhone X. Maybe the minimum value shouldn’t be dynamic. It can easily just be 1 or 2 or 3. An iPad user might like 2 or 3 images per row with the thumbnail being a medium-sized image.

![4281EB5A-50C4-4852-9042-85E79A032015](https://user-images.githubusercontent.com/11168465/172059356-124a417d-ec40-4d4d-972e-18a6776c56c5.jpeg)

**Comment by EddyLB** [comment]
The number of thumbnails displayed per row is conditioned by the image size of the selected "Thumbnail File" to avoid the situation where thumbnails look blurred. With the "Thumbnail" file selected (visible on your screenshot), the app downloads files of 144x144 pixels (default size on a Piwigo server).

The iPhone X has a screen of 1125x2436 px @3x so you get non-blurred image is you display at least 1125/144 ≈ 8 images per row. To display 4 images per row, the image size must be greater than 1125/4 = 282 pixels i.e. the XS Piwigo size. In the "Thumbnail File" section, the app tells you which is the recommended file type for your device (screenshot for an iPhone 13 Pro).

![Photo_Sizes](https://user-images.githubusercontent.com/7103032/172482078-2695260c-20ea-4725-ab19-27985520a510.png)

**Comment by pyRobShrk** [comment]
Well, this is still an issue because the app is not reading my custom image sizes. I have no use for a 144x144 thumbnail image on my server. Here are my image sizes:
![Screenshot 2022-06-07 141757](https://user-images.githubusercontent.com/11168465/172484502-9d66f1f2-d458-401f-b5a0-e0d026ba7e57.png)

**Comment by EddyLB** [comment]
You will get the number of thumbnails per row you wish by selecting the Small file type.
