### ISSUE TITLE
iOS Screen Mirroring

### ISSUE THREAD

**Issue by f1yankees** [Piwigo/Piwigo-Mobile#511]
I can't seem to get screen mirroring to work on either iOS or iPadOS so I will tag it as a new feature.  It would be great if this could be implemented as it makes sharing photos with a group of people in person really easy.

Alternatively (or maybe additionally), a tvOS application would also be great.

**Comment by Daniel-WW** [comment]
Hello, I can also support the request. You can share the screen of the piwigo-App from iPhone to Apple TV, but only the top navigation level. This means I can only see my top albums on the TV, but as soon as I go into albums below or if I open even individual photos, they are not mirrored on the TV. It would be great to find a solution to this problem.

**Comment by benjaminchodroff** [comment]
The 3.0 beta still exhibits this issue - we can see screen mirroring of the list of the albumbs, but showing individual photos or ideally a slideshow of an album is currently not possible.

**Comment by Daniel-WW** [comment]
Hi EddyLB, 
thank you very much for your great efforts and the development in terms of iOS Screen Mirroring. I did a first test in the beta 3.0 version and yes, it is possible to mirror a single photo to the Apple TV. Thank you very much! 

I noticed two useful points, which unfortunately, are not yet possible. Maybe this will be helpful for further development: 

Firstly, I can't mirror any other APP content. I don't see an album overview or album hierarchy or the photo overview of an album on the mirrored Display (Apple TV).

Secondly, I can only mirror a single photo at a time, and then I have to select the next photo in the app on the iPhone and click on it to mirror. The iPhone app always stops in the photo overview. I don't have the possibility to call up the photos one after the other and browse through the photos of an album with "Swipe left" or "Swipe right" (Comparable to the iOS photo app).

These two points would certainly be very helpful if, for example, you want to present holiday photos from one album, one after the other.

Thanks again for your great work and best regards - Daniel

**Comment by EddyLB** [comment]
Hi @Daniel-WW 

> Firstly, I can't mirror any other APP content. I don't see an album overview or album hierarchy or the photo overview of an album on the mirrored Display (Apple TV).

Indeed, we want to protect users' privacy and avoid displaying the content of the app (and device) on a large secondary screen.

> Secondly, I can only mirror a single photo at a time, and then I have to select the next photo in the app on the iPhone and click on it to mirror. The iPhone app always stops in the photo overview. I don't have the possibility to call up the photos one after the other and browse through the photos of an album with "Swipe left" or "Swipe right" (Comparable to the iOS photo app).

For this first release, the app only displays a photo/video tapped on the device but we envisage to add a few options in a near future, one of them being an automated slide show of the selected album (#182). In parallel, we also envisage to develop a Piwigo tvOS app optimised for the Apple TV and other smart TVs which will display albums and photos optimally.
