### ISSUE TITLE
[BUG] Incompatibility between Piwigo Mobile 2.11.x and Community Plugin?

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#512]
From a user using Piwigo Mobile 2.11.1 (471) on iPhone 6s — iOS 13.7

_I have Piwigo 12.2.0 running and Community Plugin 12.c installed to allow two users to upload pictures to certain albums (no other modifications)._
_Both users have the same rights in Piwigo (‚Normal') and have upload access to the same set of albums via Community and a user group defined in Piwigo. One of these users can additionally view a few more albums via album access rights, All other users are 'Generic' view only via album access rights and are not affected by the problem:_

_If I use the current versions of Piwigo App for iOS (2.11 or 2.11.1, iOS 13, 14 or 15 on iPad Air 3, iPhone SE II or iPhone 6S) the additional albums of the second 'Normal' user above do not even show up in the App, while the albums accessible via the defined user-group and the Community plugin are all displayed in the same hierarchy level and all without their album preview. Uploading pictures is still possible and pictures within the albums can be viewed normally, but the behavior does not look correct?_

_There seems to be an incompatibility between iOS-App 2.11.x and the Community plugin – if I deactivate the plugin in Piwigo, the 'Normal'/Community users can correctly see all albums again and all with their previews (but of course cannot upload any pictures anymore)._

_If useful I could provide a test account to reproduce the behavior with iOS App v2.11.x and previous versions, where everything was fine (I still have a v 2.10 iOS installed on one of my iPads, where everything works seamlessly).
Also, no problems at all when working via web interface on the PC – all albums available, upload via Community works fine._

**Comment by erhardjo** [comment]
If I understood the postRequest function correctly, in line 148 the true must also be in quotes (--> to be a string).

"recursive"         : "true",
