### ISSUE TITLE
[BUG] Settings inaccessible after restoration of default album when it is not the root album

### ISSUE THREAD

**Issue by groceryheist** [Piwigo/Piwigo-Mobile#521]
**Describe the bug and how to reproduce**
If you set the default gallery., then close and reopen the app, you cannot return to the settings menu to change the default. Nor can you see any other galleries. 

 to reproduce the behavior:
1. Go to 'settings menu'
2. Click on 'default'
3. Close the app
4. Reopen the app

**Expected behavior**
I expect that the default gallery will be visible when I open the app, and that photos I upload will upload to that gallery be default, but that it will be possible to return to the settings menu, and to view or upload to other galleries.

 I searched whether a similar issue is already reported
I did not try to test with the demo site or the guest account. 

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.6
 - App version 2.12.3

**Additional context**
 - I have the "community" extension installed, but that might not be related.
 - The server is running the latest piwigo version, but I don't want to post the url publicly, sorry.

**Comment by EddyLB** [comment]
Thanks for the feedback and sorry for this bug which we are going to fix asap.

PS: The app uploads photos to the gallery from which you tapped the [+] button.
