### ISSUE TITLE
Photos discarded from uploading pop up again when auto-upload is on

### ISSUE THREAD

**Issue by mybuntu-git2** [Piwigo/Piwigo-Mobile#527]
**Describe the bug and how to reproduce**

I have a photo in the camera roll I do not want to upload, but have to keep auto upload enabled.
(actually discovered this because there was a sync issue so a video thumbnail was in photos app but did not actually exist in iCloud)

**Expected behavior**
I discard it from the upload queue, I would expect the discard to be permanent.

actual behaviour:
every once in a while, Piwigo retries to find the image and I end up with this error pending.

**Comment by EddyLB** [comment]
Good point. This will be fixed in the next version of the app.
