### ISSUE TITLE
Better control on making "friendly / SEO" URLs which are so important to search engines.

### ISSUE THREAD

**Issue by nigel-aves** [Piwigo/Piwigo-Mobile#529]
Even when using the two options to drop .php and ? ( $conf['question_mark_in_urls'] ) the URLs are still long and not exactly friendly!  I found this post by chance " https://piwigo.org/forum/viewtopic.php?id=29076&p=1 " and a method is described for entirely dropping
"index.php? / catagory / picture.php? " and with these missing this gives us the best URL for both the friendly / SEO aspect.

I think you would have a lot of happy users if this was implemented with options in te interface to trigger (though I think on a vote everyone would like this as default) and the .htaccess workaround to convert back could / should be hidden in .php code (that would be the best way of doing it. 

Just food for thought.

**Comment by EddyLB** [comment]
The iOS app retrieves image URLs from the Piwigo server. So if the API methods provide "friendly" URLs, the iOS app will use them and should work without having to recode things. I therefore close this issue but feel free to reopen it with details showing that is not the case if necessary.
