### ISSUE TITLE
File prefix not working?

### ISSUE THREAD

**Issue by mybuntu-git2** [Piwigo/Piwigo-Mobile#531]
Hi,
 it seems photos are no longer prefixed since last release?

also a question. If I prefix photos, I can move them to galleries based on prefix and then run remote_sync.pl, or that would massively break the uploads folder for missing files?

thee above would be a simple solution for uploads folder not being isolated by source.

**Comment by EddyLB** [comment]
Hi @mybuntu-git2 
I have just uploaded photos with the version 2.12.7 build 496 of the app currently available on the App Store and the prefix is well added to filenames. So it looks that I can close this issue.

As for your second version, I do not know the server app enough to answer properly your question. I therefore invite you to post it on the [forums](https://piwigo.org/forum/index.php).
