### ISSUE TITLE
[BETA 3.0] Feedback | Random crash while loading images

### ISSUE THREAD

**Issue by benjaminchodroff** [Piwigo/Piwigo-Mobile#533]
**Describe the bug and how to reproduce**
Application crash while loading many images into cache

Load photos from https://benchodroff.com/photos/ without login, and open Guizhou 2023 albumb
Start swiping across each photo to start loading them all into cache
Application will crash

**Expected behavior**
No crash

**What did you do already**
Tried again, keeps crashing

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: 16.4.1 (a)
 - App version: Beta 3.0

**Comment by EddyLB** [comment]
@benjaminchodroff 
I am unable to reproduce the crash with the simulator and my devices. Most downloads fail because of a network timeout and that's it.

The default size for previewing photos on an iPhone 12 Pro Max is "Full Resolution" which leads to the download of large files. Can you please select the Photos / Preview File size "Huge" instead of "Full resolution" in Settings as shown below and tell me if the app still crashes. 

![image](https://user-images.githubusercontent.com/7103032/236628564-9582af95-6a26-4286-a31d-4ed01d843c9c.png)

**Comment by benjaminchodroff** [comment]
Switching to Huge fixed the problem - no more crashes. Switching back to Full Resolution (even though all the photos are cached) causes the crash to reappear.

**Comment by EddyLB** [comment]
Thank you very much for the tests. 
Have you reported the crashes with TestFlight? I would like to try to fix this issue.

**Comment by benjaminchodroff** [comment]
Oddly enough, this particular crash is not triggering any TestFlight notice to send logs. The app completely disappears and I'm back at home - but the app is still running. Not sure what else to try!

**Comment by EddyLB** [comment]
Thank you for the infos.
Could you please repeat the same tests with this [Piwigo website](https://piwigo.lelievre-berna.net/Dev/).

**Comment by benjaminchodroff** [comment]
I hit every photo in every album in the piwigo website, but sadly the crash did not happen even though I had it set to full resolution. I guess it may either be related to either my cache size for my website was very large (over 2GB for mine, whereas yours is only caching ~150MB for photos), or the size of my full resolution photos are much larger than yours (mine can easily be >20MB at full resolution)

**Comment by benjaminchodroff** [comment]
After setting it back to my Piwigo, and swiping very quickly through Guizhou 2023 with a clear cache, it soft crashed again. It appears to be related to the large photo size and swiping very quickly. I tried multiple other albums and was unable to reproduce the crash.

**Comment by EddyLB** [comment]
Thank you @benjaminchodroff for these tests. 
I will try to reproduce them with very large photos.

**Comment by EddyLB** [comment]
Hi @benjaminchodroff 
After some investigations, the crash is due to the amount of RAM required to handle very large photos. iOS kills the app when it starts using too much memory. The next build of the version 3.0 will fix this issue.

**Comment by benjaminchodroff** [comment]
Confirmed, the latest build has fixed the issue. Thank you!

**Comment by EddyLB** [comment]
Great! Thank you.
