### ISSUE TITLE
UI Improvement | Order coherency

### ISSUE THREAD

**Issue by Phil353556** [Piwigo/Piwigo-Mobile#552]
using the mobile phone or the browser  doesn't display in the same order.

mobile:     note that the "Envoyer" do not work,   should go back to "Propriétés" then "envoyer" is Ok.
![image](https://github.com/Piwigo/Piwigo-Mobile/assets/64729485/4784a8e6-54aa-4ee0-a6b4-330f35e09b97)

browser:
![Capture d’écran du 2023-09-11 11-59-08](https://github.com/Piwigo/Piwigo-Mobile/assets/64729485/2d85312b-ddfa-4938-984a-0f4ec80fbada)

**Comment by EddyLB** [comment]
Good point. 
We are going to reverse the order.

**Comment by Phil353556** [comment]
Thank you!
