### ISSUE TITLE
Album and photo rights

### ISSUE THREAD

**Issue by Phil353556** [Piwigo/Piwigo-Mobile#553]
Hi,

using IOS Testflight 3.1 (536) with piwigo server 13.8.0

during import phase, choice made is "admins, Famille"

When I look at the same information on a browser it is displayed: "public"  however it seems not really "public" ... strange 
![image](https://github.com/Piwigo/Piwigo-Mobile/assets/64729485/60873d70-1a74-460f-99ce-ff062779cbfb)

Is it possible to go deeper on rights with groups and users, using the mobile phone?

Thank you

**Comment by EddyLB** [comment]
"Admins, Famille, etc." apply to photos an "public/private" options apply to albums. So there is no bug here. 

But it is true that the iOS app does not manage private albums, nor users and groups. This is in our to-do list.

**Comment by EddyLB** [comment]
Hi @Phil353556 

When uploading photos to a public album, one can choose to set photos as accessible to everyone or not.

When syncing a folder structure, the selected access option applies to **both** photos and folders (i.e. albums) into which they are located. This is the reason why the album(s) become(s) private when the chosen option is not 'everyone'.

I therefore believe that this issue can be closed.
