### ISSUE TITLE
[BUG] HEVC videos not uploaded in MP4 format...again?

### ISSUE THREAD

**Issue by sorenweber** [Piwigo/Piwigo-Mobile#567]
According to [Configure Piwigo for Uploading Videos](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos) videos in HEVC format should be uploaded in a more compatible format, but it does not appear to do so. It was addressed in #335 but now it doesn't seem to work.

If the iPhone is set to store in "High Efficiency", the video is encoded in HEVC and in a MOV container. For better compatibility it should be possible to choose that the video is converted and uploaded encoded in h.264 in a MP4 container. Or that it is just forced if in HEVC, MOV.

I don't know if it matters but I have added MOV to the list of allowed containers in Piwigo as part of my investigation why I couldn't upload videos. I have also followed this guide [How-to-add-videos](https://github.com/Piwigo/piwigo-videojs/wiki/How-to-add-videos).

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.3
 - App version 3.1.2
 - Piwigo server 14.2

**Comment by EddyLB** [comment]
When you allow the MOV QuickTime file format in your Piwigo server with [LocalFiles Editor](https://piwigo.org/ext/extension_view.php?eid=144), you explicitly allow the iOS app to upload videos without converting them to the MPEG-4/H.264 video format.

I have re-checked the current version of the app (3.1.2) and confirm that it converts HEVC and Apple ProRes videos when MOV is not allowed by the Piwigo server. I therefore close this issue.

**Comment by sorenweber** [comment]
Thank you, you are completely correct. I have now removed the reference to 'mov' everywhere (in the config and in the plugin piwigo-videojs where I was messing around) and the conversion is done automatically. Sorry for the inconvenience.

**Comment by EddyLB** [comment]
No problem.
