### ISSUE TITLE
Choose Image Size for Image Detail

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#57]
User have the ability to choose the default size of the image that is displayed. Like:
XXS - tiny        
XS - extra small        
S - small        
M - medium        
L - large        
XL - extra large        
XXL - huge

**Comment by plegall** [comment]
On the "quality side" the best is to use the biggest size as possible (XXL on an iPad and maybe XL only on an iPhone). On the "speed side", depending on the connection (Wifi or 3G/4G) downloading an XXL is not a good idea.

Maybe an "automatic" setting would be good and keep the ability to use another size.

**Comment by SpencerBaker** [comment]
Implemented the ability to set a default preview image size from the settings.
76f1413c9c77609afefcee53b9c209b7f96d4cae
