### ISSUE TITLE
Resize Photo to Max Width/ Height

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#60]
Change the resize photo to not be a percentage but an actual maximum width or height.

**Comment by plegall** [comment]
Didn't you implement it with issue #59 ?

**Comment by EddyLB** [comment]
Yes, that is implemented. The app performs an affine transform of the image, the same scale applied to both width and height. However, the transform is then systematically followed by a JPEG compression with a maximum quality factor of 98%, leading to issue #195.
