### ISSUE TITLE
Crash on Loading Local Albums

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#67]
When a user loaded their local albums, the application crashed.

**Comment by kcergfalo** [comment]
I could not recreate the crash so please treat my pull request #69 as a "should solve it" fix. The code is in c311174

**Comment by SpencerBaker** [comment]
Fixed. 2940d2d3f8c5b9567d4a1ce8b3c0f3da691aa160

**Comment by SpencerBaker** [comment]
Added more safe checking. fdafd82666348002c95d69a73b39c750b46de17f
