### ISSUE TITLE
Autoupload from camera roll

### ISSUE THREAD

**Issue by norbusan** [Piwigo/Piwigo-Mobile#70]
Would be nice to have a feature to automatically upload new camera roll photos to a selectable gallery.

**Comment by SpencerBaker** [comment]
I assume this would be a "one tap" option? Where you setup which album to pull new images from and which album to upload to, then from one tap it just sets them in an upload queue and starts it?
 - No option to edit information (tags, description, name)

I like it because that's what I mainly use Piwigo for. ;)

**Comment by norbusan** [comment]
Hi Spencer

yes, your idea sounds good as well. Another option would be an automatic background upload of new photos.

The Plex iOS app is doing this: As soon as you start the app it check and uploads new files, while one can watch something else.

But in the Piwigo app a button that selects new photos, puts them in the upload queue, and drop you there. From there you can simply press the usual upload button or edit some parameters.

Thanks

**Comment by SpencerBaker** [comment]
Ah okay. I like the idea. 

By the way, when images are being uploaded, you can press "Done" and go back to the app and browse while the images are being uploaded -- if you didn't know.

**Comment by norbusan** [comment]
Hi Spencer

thanks, didn't realize that this works (and never tried ;-).

**Comment by gpitel** [comment]
We are about to retire our piwigo server because of the lack this feature.  Its available in Google Photos. When I enter the app it automatically copy to cloud.

I just can't get my family members to manually move their photos from their camera roll to the server, both for sharing, and backup.

**Comment by dnfalk** [comment]
Has there been any update to this? Thanks!

**Comment by NicolasHaeffner** [comment]
This is the only thing holding me back from switching to piwigo. 
A lot of Apps (Nextcloud for instance) even check your location once in a while just to wake up the process in the background to upload new media. 

And maybe a "only on wifi" Option would benefit a lot of people too, if you are going to implement that.

**Comment by EddyLB** [comment]
We are finalising a new version which will bring (we hope) a better uploading experience. The “only WiFi” is certainly an option to consider and we thank you for this suggestion. 

We agree that the upload of images taken with camera apps must be facilitated. But we shall first add a camera option to the app to upload them immediately. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by exekutive** [comment]
I would also like to designate a specific photos album which will upload automatically, without having to queue it up manually.  

I am not interested in uploading EVERY photo. They're not all suitable for publishing.

**Comment by Eguun** [comment]
Likewise,

Google photos announced its end of free & unlimited quota when backing up photos.
Looking for an alternative; IOS autoupload of the camera roll is a must-have.

Watching this thread to see when this feature is implemented

**Comment by sarunasil** [comment]
Most interested in resurrecting this thread/request! I imagine it would be enabled in settings and when a new image is created, the app would upload it to the cloud (if all requirements are met e.g. wifi present when 'wifi only' is enabled). Essentially, duplicating the workflow of google photos and the convenience it entails

**Comment by bajancode** [comment]
Thanks for taking this on @EddyLB ! I would like to switch to Piwigo as well but this is the only thing holding me back.
