### ISSUE TITLE
upload does not work starting from 2.0 (7)

### ISSUE THREAD

**Issue by norbusan** [Piwigo/Piwigo-Mobile#75]
Hi,

since version 2.0 (7) every time I try to upload a file, the application crashes. After selecting an album, then click the upload button, select a photo from the film roll, I end up in the upload screen where name and uploader and privacy can be selected.

Then I click on the upload button in the top right and bang, the application crashes.

I *could* upload to my installation till version 2.0 (6), though.

**Comment by SpencerBaker** [comment]
Is the device you're running Piwigo on an iPhone 4S? If not, what is it?
I currently only have a crash report for that phone and it looks like it came from one user. I might not have gotten your crash report yet, but I'll look again tomorrow.

Thanks for the bug submission though!

**Comment by norbusan** [comment]
Hi Spencer,

sorry for the incomplete infos: iPhone 5s, iOS 8.1.2 jailbroken. So if you need some files from the drive, I can easily get them.

I haven't contacted you about this before. 

Thanks

Norbert

**Comment by SpencerBaker** [comment]
Hey Norbusan,
Okay, I'll check tomorrow for when your crash report(s) upload to Apple. If I need more information, I'll ask for it here.
Thanks!

**Comment by kcergfalo** [comment]
Hi Norbert, Hi Spencer,
I am seeing a crash on upload too. Just now I am stepping through the code and will update once have I narrowed it down.

Thanks

**Comment by kcergfalo** [comment]
Hi Norbert,

could you please go to the settings screen and check the setting of the "Photo Size" and tell me if it is on 1%? 
Then leave the setting screen try again to upload. 

Thanks
Olaf

**Comment by SpencerBaker** [comment]
Fixed. 32c1e8eeaef5418d00184918ea34ed1c5e650aec

**Comment by norbusan** [comment]
Hi all

first I confirm that it is fixed, thanks!

Concerning the 1% thing:
* on v7 I saw 100%, but it crashed
* then today I updated to v8
* then the size was at 1% but upload worked (at 1% size ;-)
* now upload at 100% also work

Big thanks again

Norbert
