### ISSUE TITLE
Redesign the Album Cell

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#80]
Redesign the album cell to:
- Display most/ all of the image representation
- Clearly display the album details
- Clean it up

**Comment by Tadjio** [comment]
Can I suggest you compare the Smartpocket Mobile Theme layout for Album Thumbnails?
I believe this is a good starting point.
(We need to consider the Photo Thumbnails layout and the detail Photo Display as separate issues).

**Comment by Tadjio** [comment]
Here are my Album Thumbnails screens from Piwigo iOS 2.0 and from Smartpocket Theme...
![img_2651](https://cloud.githubusercontent.com/assets/9560497/7188094/31bfab08-e46d-11e4-831e-cb6fce927e40.PNG)
![img_2652](https://cloud.githubusercontent.com/assets/9560497/7188100/3fbae628-e46d-11e4-975a-53f717ae461c.PNG)

**Comment by plegall** [comment]
I like the new design :-) (I liked the previous one too)

![img_4422](https://user-images.githubusercontent.com/9326959/44520913-a87dea00-a6d1-11e8-9f6d-d386c851b82d.PNG)

**Comment by plegall** [comment]
The "no comment" is not the correct wording. The right one would be "no description" or "edit to add a description" or nothing at all (why saying there is nothing to say). In Piwigo "comment" is for "user comment".

**Comment by EddyLB** [comment]
Good point! Thank you. I'm going to replace "no comment" with "no description".
I will leave this string so that the cell is less "empty" and more importantly to invite people to add descriptions. Albums and photos without descriptions can become useless if there is nobody to tell what happened.

**Comment by plegall** [comment]
If you see the Piwigo iOS app as an admin tool, then yes having the "no description" is a good idea. If you see it more as a "native theme for gallery instead of using Safari", then I think the "no description" is "less a good idea" ;-)

**Comment by EddyLB** [comment]
Good point. So the best might be to display it when the user can edit it and to remove empty descriptions for others. Agreed ?

**Comment by plegall** [comment]
I think it's a good compromise :-)
