### ISSUE TITLE
No indication of upload progress when "Done" is clicked

### ISSUE THREAD

**Issue by norbusan** [Piwigo/Piwigo-Mobile#81]
When selecting some photos to upload, press "Upload" in the queue screen, and then click "Done" there is no indication whatsoever whether it is still uploading, and how long, and how is the progress. I.e., there is no way to return to the upload screen (AFAIS).

Thanks!

**Comment by SpencerBaker** [comment]
There's no way to return, unless you select more images to upload, then the other images that are uploading will be displayed.

![ios simulator screen shot apr 16 2015 8 55 21 pm](https://cloud.githubusercontent.com/assets/6547671/7195320/eb695632-e47a-11e4-8c30-deef7b139f30.png)

Do you not have the upload bar at the bottom shown in this screen shot?

**Comment by norbusan** [comment]
Ahhh, ok. I didn't check that one can go back to the upload selection screen to see the ones being uploaded. I will retry. 

I guess that can be closed, then.
