### ISSUE TITLE
Upload error with v9

### ISSUE THREAD

**Issue by norbusan** [Piwigo/Piwigo-Mobile#82]
I just tried uploading with the new version (v9) and it seemed some photos were properly uploaded, but then I got

Could not upload your image. Error: An SSL error has occurred and a secure connection to the server cannot be made.

And another screen

Upload Error: Could not upload your image. Error: request body stream exhausted.

After that I terminated the app, reentered it and realized that 3 images were not uploaded, but could upload. Checking back the contents one of the image was half grey (one of those in the first upload batch).

**Comment by SpencerBaker** [comment]
Are you using an https server? And I take it it wasn't doing this before?

**Comment by norbusan** [comment]
Yes, I am using an https server. And I was always using an https server. I am not sure if it was working before, because it seems to depend on the amount of photos to be uploaded, as it was not the first photo that failed but one of the last of about 30.

**Comment by SpencerBaker** [comment]
Oh, that's interesting... It does weird things if your internet connection drops.

**Comment by norbusan** [comment]
On my server I can check everything (it is *my* server ;-), but on the iOS side I have not much experience to debug.
