### ISSUE TITLE
Scrolling in an album sometimes does not refresh the photos

### ISSUE THREAD

**Issue by norbusan** [Piwigo/Piwigo-Mobile#83]
I just scrolled through one album, and when scrolling back _upward_ the first photos didn't get displayed again, just the background was shown.

I couldn't repeat it, though, despite some heavy trying ;-) Just wanted to report it. Please close if you find it too unclear.

**Comment by EddyLB** [comment]
Indeed, sometimes images do not appear or seem lost and cannot easily be reloaded. Killing and relaunching the app seems to be the only fix.

**Comment by EddyLB** [comment]
Fixed in release 2.0.4.
