### ISSUE TITLE
Move Image to another Album

### ISSUE THREAD

**Issue by SpencerBaker** [Piwigo/Piwigo-Mobile#88]
Ability to move an image from one album to another.

One thing to note: images that are tied to more than one album.

**Comment by kcergfalo** [comment]
Branch iPad_Albums_Page now can move image to multiple albums.
I am working on two bugs:
- after move, when entering previous album app will loop in AlbumData:loadMoreImagesOnCompletion
- when receiving imagedata from the server not all albumIDs are attached to an image in ImageService:parseBasicImageInfoJSON

If you find more issues please feel free to update.

**Comment by kcergfalo** [comment]
commit 63f0be33c fixes the endless loop in AlbumData:loadMoreImagesOnCompletion

On the iPhone the moved image is still displayed in the old album.
