### ISSUE TITLE
unexpected video upload

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Mobile#93]
On a Piwigo where video upload is not active, Piwigo Mobile let you select a video from iphone but only a small JPEG thumbnail is uploaded. If the video upload is not permitted Piwigo Mobile should not propose to upload it.

**Comment by plegall** [comment]
and when I activate the video upload:

$conf['upload_form_all_types'] = true;
$conf['file_ext'] = array_merge(
  $conf['picture_ext'],
  array('mov', 'MOV')
  );

I have the same behavior: the video is not uploaded, only a small thumbnail.

**Comment by EddyLB** [comment]
To my knowledge, the only way to know if one can upload videos is to check whether VideoJS is installed with the `pwg.plugins.getList` method. This requires admin rights and this is implemented in release 2.0.4. (see 355ff69).

**Comment by EddyLB** [comment]
As suggested by @plegall , as from v2.1.2 the iOS app determines if videos can be uploaded from `upload_file_types` returned by the Web API method `pwg.session.getStatus`.
