### ISSUE TITLE
delete selected images 

### ISSUE THREAD

**Issue by 1xhabit** [Piwigo/Piwigo-Mobile#94]
hello, i'm using the current iOS version from the App Store. i'dont know this is a bug or i'was done something wrong. if try to delete my own images i get a fail 401 error with the message i'm not authorized 
this to do. 

maybe someone can help ... ??

sincerely
xhabit

**Comment by SpencerBaker** [comment]
You're getting a 401 because the user you're logged in as doesn't have permission from Piwigo to delete the image. You have to have "Admins" privacy level, I think. I know if you're logged in as the "webmaster" then you can.
