### ISSUE TITLE
Crash encountered when adding tag to photo before upload 

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#96]
Here is how to crash the app with iOS 9.1:
1. Tap on Upload
2. Select an album to upload images to
3. Select a local album
4. Select an image and tap on the Upload icon 
5. Edit the image to upload and tap on the Tags field
6. Select a tag

**Comment by SpencerBaker** [comment]
Confirmed.
Thanks!

**Comment by EddyLB** [comment]
I suggested a fix. Can it be implemented and distributed ?

**Comment by SpencerBaker** [comment]
Hi Eddy,
Your fix looks great, but unfortunately I don't have credentials to push Piwigo to the App Store any more.
I would need to get them again from @plegall to deploy a new version.

**Comment by EddyLB** [comment]
Thanks Spencer. I contact him.

**Comment by jradwan** [comment]
Did this ever make it into the App Store version? Just ran into this same crash today but not sure if the iOS app is even supported anymore.

**Comment by EddyLB** [comment]
I've contacted the developer and then Pierrick Le Gal to determine how I could upload and share my fix. I got a few positive answers and finally no more replies. Really a shame...

**Comment by plegall** [comment]
Hi @EddyLB I'm going to check all this today.
